/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Animation2                                            *
* Dimensions:  13 * 72                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmAnimation2;

static GUI_CONST_STORAGE unsigned char _acAnimation2[] = {
  /* RLE: 030 Pixels @ 000,000 */ 30, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 004,002 */ 5, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 009,002 */ 7, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,003 */ 7, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 010,003 */ 5, 0xC0, 0x51, 
  /* RLE: 009 Pixels @ 002,004 */ 9, 0xFF, 0xFF, 
  /* RLE: 003 Pixels @ 011,004 */ 3, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,005 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,005 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,006 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,006 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,007 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,007 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,008 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,008 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,009 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,009 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,010 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,010 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,011 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,011 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,012 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,012 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,013 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,013 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,014 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,014 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,015 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,015 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,016 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,016 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,017 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,017 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,018 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,018 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,019 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,019 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,020 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,020 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,021 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,021 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,022 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,022 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,023 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,023 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,024 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,024 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,025 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,025 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,026 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,026 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,027 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,027 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,028 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,028 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,029 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,029 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,030 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,030 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,031 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,031 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,032 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,032 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,033 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,033 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,034 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,034 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,035 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,035 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,036 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,036 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,037 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,037 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,038 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,038 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,039 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,039 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,040 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,040 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,041 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,041 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,042 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,042 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,043 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,043 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,044 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,044 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,045 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,045 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,046 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,046 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,047 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,047 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,048 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,048 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,049 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,049 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,050 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,050 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,051 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,051 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,052 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,052 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,053 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,053 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,054 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,054 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,055 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,055 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,056 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,056 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,057 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,057 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,058 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,058 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,059 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,059 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,060 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,060 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,061 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,061 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,062 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,062 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,063 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,063 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,064 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,064 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,065 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,065 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,066 */ 11, 0xFF, 0xFF, 
  /* ABS: 002 Pixels @ 012,066 */ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 001,067 */ 11, 0xFF, 0xFF, 
  /* RLE: 003 Pixels @ 012,067 */ 3, 0xC0, 0x51, 
  /* RLE: 009 Pixels @ 002,068 */ 9, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 011,068 */ 5, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,069 */ 7, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 010,069 */ 7, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 004,070 */ 5, 0xFF, 0xFF, 
  /* RLE: 017 Pixels @ 009,070 */ 17, 0xC0, 0x51, 
  0
};  // 526 for 936 pixels

GUI_CONST_STORAGE GUI_BITMAP bmAnimation2 = {
  13, // xSize
  72, // ySize
  26, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acAnimation2,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
