/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.16.                           *
*        Compiled Jun  4 2012, 15:48:30                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: animationAlarm2                                       *
* Dimensions:  14 * 63                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned char acanimationAlarm2[] = {
  /* RLE: 032 Pixels @ 000,000*/ 32, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 004,002*/ 5, 0xC0, 0x51, 
  /* RLE: 008 Pixels @ 009,002*/ 8, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 003,003*/ 7, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 010,003*/ 6, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 002,004*/ 9, 0xC0, 0x51, 
  /* RLE: 004 Pixels @ 011,004*/ 4, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,005*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,005*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,006*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,006*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,007*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,007*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,008*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,008*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,009*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,009*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,010*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,010*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,011*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,011*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,012*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,012*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,013*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,013*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,014*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,014*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,015*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,015*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,016*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,016*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,017*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,017*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,018*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,018*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,019*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,019*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,020*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,020*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,021*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,021*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,022*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,022*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,023*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,023*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,024*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,024*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,025*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,025*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,026*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,026*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,027*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,027*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,028*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,028*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,029*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,029*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,030*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,030*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,031*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,031*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,032*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,032*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,033*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,033*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,034*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,034*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,035*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,035*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,036*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,036*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,037*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,037*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,038*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,038*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,039*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,039*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,040*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,040*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,041*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,041*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,042*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,042*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,043*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,043*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,044*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,044*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,045*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,045*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,046*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,046*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,047*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,047*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,048*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,048*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,049*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,049*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,050*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,050*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,051*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,051*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,052*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,052*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,053*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,053*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,054*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,054*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,055*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,055*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,056*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,056*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,057*/ 11, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 012,057*/ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 001,058*/ 11, 0xC0, 0x51, 
  /* RLE: 004 Pixels @ 012,058*/ 4, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 002,059*/ 9, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 011,059*/ 6, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 003,060*/ 7, 0xC0, 0x51, 
  /* RLE: 008 Pixels @ 010,060*/ 8, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 004,061*/ 5, 0xC0, 0x51, 
  /* RLE: 019 Pixels @ 009,061*/ 19, 0xFF, 0xFF, 


  0};  /* 242 for 882 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmanimationAlarm2 = {
  14, /* XSize */
  63, /* YSize */
  28, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)acanimationAlarm2,  /* Pointer to picture data */
  NULL,  /* Pointer to palette */
  GUI_DRAW_RLE16
};

/* *** End of file *** */
