/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: AroundCharging                                        *
* Dimensions:  21 * 22                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmAroundCharging;

static GUI_CONST_STORAGE unsigned char _acAroundCharging[] = {
  /* RLE: 049 Pixels @ 000,000 */ 49, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 007,002 */ 7, 0xFF, 0xFF, 
  /* RLE: 012 Pixels @ 014,002 */ 12, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 005,003 */ 11, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 016,003 */ 9, 0xC0, 0x51, 
  /* RLE: 004 Pixels @ 004,004 */ 4, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 008,004 */ 5, 0x75, 0x06, 
  /* RLE: 004 Pixels @ 013,004 */ 4, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 017,004 */ 7, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 003,005 */ 3, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 006,005 */ 9, 0x75, 0x06, 
  /* RLE: 003 Pixels @ 015,005 */ 3, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 018,005 */ 5, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 002,006 */ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 005,006 */ 11, 0x75, 0x06, 
  /* RLE: 003 Pixels @ 016,006 */ 3, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 019,006 */ 4, 0xC0, 0x51, 
  /* ABS: 002 Pixels @ 002,007 */ 0, 2, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 004,007 */ 13, 0x75, 0x06, 
  /* ABS: 008 Pixels @ 017,007 */ 0, 8, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x51, 0xC0, 0x51, 0xC0, 0x51, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 004,008 */ 13, 0x75, 0x06, 
  /* RLE: 003 Pixels @ 017,008 */ 3, 0xFF, 0xFF, 
  /* ABS: 004 Pixels @ 020,008 */ 0, 4, 0xC0, 0x51, 0xC0, 0x51, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 015 Pixels @ 003,009 */ 15, 0x75, 0x06, 
  /* ABS: 006 Pixels @ 018,009 */ 0, 6, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x51, 0xC0, 0x51, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 015 Pixels @ 003,010 */ 15, 0x75, 0x06, 
  /* ABS: 006 Pixels @ 018,010 */ 0, 6, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x51, 0xC0, 0x51, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 015 Pixels @ 003,011 */ 15, 0x75, 0x06, 
  /* ABS: 006 Pixels @ 018,011 */ 0, 6, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x51, 0xC0, 0x51, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 015 Pixels @ 003,012 */ 15, 0x75, 0x06, 
  /* ABS: 006 Pixels @ 018,012 */ 0, 6, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x51, 0xC0, 0x51, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 015 Pixels @ 003,013 */ 15, 0x75, 0x06, 
  /* ABS: 007 Pixels @ 018,013 */ 0, 7, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x51, 0xC0, 0x51, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 004,014 */ 13, 0x75, 0x06, 
  /* RLE: 003 Pixels @ 017,014 */ 3, 0xFF, 0xFF, 
  /* RLE: 003 Pixels @ 020,014 */ 3, 0xC0, 0x51, 
  /* ABS: 002 Pixels @ 002,015 */ 0, 2, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 013 Pixels @ 004,015 */ 13, 0x75, 0x06, 
  /* ABS: 002 Pixels @ 017,015 */ 0, 2, 0xFF, 0xFF, 0xFF, 0xFF, 
  /* RLE: 004 Pixels @ 019,015 */ 4, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 002,016 */ 3, 0xFF, 0xFF, 
  /* RLE: 011 Pixels @ 005,016 */ 11, 0x75, 0x06, 
  /* RLE: 003 Pixels @ 016,016 */ 3, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 019,016 */ 5, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 003,017 */ 3, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 006,017 */ 9, 0x75, 0x06, 
  /* RLE: 003 Pixels @ 015,017 */ 3, 0xFF, 0xFF, 
  /* RLE: 007 Pixels @ 018,017 */ 7, 0xC0, 0x51, 
  /* RLE: 004 Pixels @ 004,018 */ 4, 0xFF, 0xFF, 
  /* RLE: 005 Pixels @ 008,018 */ 5, 0x75, 0x06, 
  /* RLE: 004 Pixels @ 013,018 */ 4, 0xFF, 0xFF, 
  /* RLE: 009 Pixels @ 017,018 */ 9, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 005,019 */ 11, 0xFF, 0xFF, 
  /* RLE: 012 Pixels @ 016,019 */ 12, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 007,020 */ 7, 0xFF, 0xFF, 
  /* RLE: 028 Pixels @ 014,020 */ 28, 0xC0, 0x51, 
  0
};  // 210 for 462 pixels

GUI_CONST_STORAGE GUI_BITMAP bmAroundCharging = {
  21, // xSize
  22, // ySize
  42, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acAroundCharging,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
