/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.22.                           *
*        Compiled Jul  4 2013, 12:18:24                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Charging                                              *
* Dimensions:  29 * 40                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmCharging;

static GUI_CONST_STORAGE unsigned char _acCharging[] = {
  /* RLE: 141 Pixels @ 000,000 */ 141, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 025,004 */ 3, 0x46, 0xB4, 
  /* RLE: 025 Pixels @ 028,004 */ 25, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 024,005 */ 3, 0x46, 0xB4, 
  /* RLE: 025 Pixels @ 027,005 */ 25, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 023,006 */ 3, 0x46, 0xB4, 
  /* RLE: 024 Pixels @ 026,006 */ 24, 0xC0, 0x51, 
  /* RLE: 004 Pixels @ 021,007 */ 4, 0x46, 0xB4, 
  /* RLE: 024 Pixels @ 025,007 */ 24, 0xC0, 0x51, 
  /* RLE: 004 Pixels @ 020,008 */ 4, 0x46, 0xB4, 
  /* RLE: 024 Pixels @ 024,008 */ 24, 0xC0, 0x51, 
  /* RLE: 004 Pixels @ 019,009 */ 4, 0x46, 0xB4, 
  /* RLE: 024 Pixels @ 023,009 */ 24, 0xC0, 0x51, 
  /* RLE: 004 Pixels @ 018,010 */ 4, 0x46, 0xB4, 
  /* RLE: 023 Pixels @ 022,010 */ 23, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 016,011 */ 5, 0x46, 0xB4, 
  /* RLE: 023 Pixels @ 021,011 */ 23, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 015,012 */ 5, 0x46, 0xB4, 
  /* RLE: 023 Pixels @ 020,012 */ 23, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 014,013 */ 5, 0x46, 0xB4, 
  /* RLE: 023 Pixels @ 019,013 */ 23, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 013,014 */ 5, 0x46, 0xB4, 
  /* RLE: 022 Pixels @ 018,014 */ 22, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 011,015 */ 6, 0x46, 0xB4, 
  /* RLE: 022 Pixels @ 017,015 */ 22, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 010,016 */ 6, 0x46, 0xB4, 
  /* RLE: 022 Pixels @ 016,016 */ 22, 0xC0, 0x51, 
  /* RLE: 008 Pixels @ 009,017 */ 8, 0x46, 0xB4, 
  /* RLE: 020 Pixels @ 017,017 */ 20, 0xC0, 0x51, 
  /* RLE: 011 Pixels @ 008,018 */ 11, 0x46, 0xB4, 
  /* RLE: 016 Pixels @ 019,018 */ 16, 0xC0, 0x51, 
  /* RLE: 015 Pixels @ 006,019 */ 15, 0x46, 0xB4, 
  /* RLE: 013 Pixels @ 021,019 */ 13, 0xC0, 0x51, 
  /* RLE: 018 Pixels @ 005,020 */ 18, 0x46, 0xB4, 
  /* RLE: 013 Pixels @ 023,020 */ 13, 0xC0, 0x51, 
  /* RLE: 019 Pixels @ 007,021 */ 19, 0x46, 0xB4, 
  /* RLE: 012 Pixels @ 026,021 */ 12, 0xC0, 0x51, 
  /* RLE: 016 Pixels @ 009,022 */ 16, 0x46, 0xB4, 
  /* RLE: 015 Pixels @ 025,022 */ 15, 0xC0, 0x51, 
  /* RLE: 012 Pixels @ 011,023 */ 12, 0x46, 0xB4, 
  /* RLE: 019 Pixels @ 023,023 */ 19, 0xC0, 0x51, 
  /* RLE: 009 Pixels @ 013,024 */ 9, 0x46, 0xB4, 
  /* RLE: 021 Pixels @ 022,024 */ 21, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 014,025 */ 7, 0x46, 0xB4, 
  /* RLE: 021 Pixels @ 021,025 */ 21, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 013,026 */ 7, 0x46, 0xB4, 
  /* RLE: 021 Pixels @ 020,026 */ 21, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 012,027 */ 6, 0x46, 0xB4, 
  /* RLE: 022 Pixels @ 018,027 */ 22, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 011,028 */ 6, 0x46, 0xB4, 
  /* RLE: 022 Pixels @ 017,028 */ 22, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 010,029 */ 6, 0x46, 0xB4, 
  /* RLE: 022 Pixels @ 016,029 */ 22, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 009,030 */ 6, 0x46, 0xB4, 
  /* RLE: 022 Pixels @ 015,030 */ 22, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 008,031 */ 5, 0x46, 0xB4, 
  /* RLE: 023 Pixels @ 013,031 */ 23, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 007,032 */ 5, 0x46, 0xB4, 
  /* RLE: 023 Pixels @ 012,032 */ 23, 0xC0, 0x51, 
  /* RLE: 004 Pixels @ 006,033 */ 4, 0x46, 0xB4, 
  /* RLE: 024 Pixels @ 010,033 */ 24, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 005,034 */ 3, 0x46, 0xB4, 
  /* RLE: 025 Pixels @ 008,034 */ 25, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 004,035 */ 3, 0x46, 0xB4, 
  /* RLE: 025 Pixels @ 007,035 */ 25, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 003,036 */ 3, 0x46, 0xB4, 
  /* RLE: 025 Pixels @ 006,036 */ 25, 0xC0, 0x51, 
  /* RLE: 003 Pixels @ 002,037 */ 3, 0x46, 0xB4, 
  /* RLE: 082 Pixels @ 005,037 */ 82, 0xC0, 0x51, 
  0
};  // 138 for 1160 pixels

GUI_CONST_STORAGE GUI_BITMAP bmCharging = {
  29, // xSize
  40, // ySize
  58, // BytesPerLine
  16, // BitsPerPixel
  (unsigned char *)_acCharging,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE16
};

/*************************** End of file ****************************/
