/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap converter for emWin V5.16.                           *
*        Compiled Jun  4 2012, 15:48:30                              *
*        (C) 1998 - 2010 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: childlock                                             *
* Dimensions:  71 * 32                                               *
* NumColors:   16bpp: 65536                                          *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif


static GUI_CONST_STORAGE unsigned char acchildlock[] = {
  /* RLE: 337 Pixels @ 000,000*/ 254, 0xC0, 0x51, 83, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 053,004*/ 6, 0xF7, 0xBD, 
  /* RLE: 062 Pixels @ 059,004*/ 62, 0xC0, 0x51, 
  /* RLE: 012 Pixels @ 050,005*/ 12, 0xF7, 0xBD, 
  /* RLE: 058 Pixels @ 062,005*/ 58, 0xC0, 0x51, 
  /* RLE: 014 Pixels @ 049,006*/ 14, 0xF7, 0xBD, 
  /* RLE: 056 Pixels @ 063,006*/ 56, 0xC0, 0x51, 
  /* RLE: 016 Pixels @ 048,007*/ 16, 0xF7, 0xBD, 
  /* RLE: 054 Pixels @ 064,007*/ 54, 0xC0, 0x51, 
  /* RLE: 018 Pixels @ 047,008*/ 18, 0xF7, 0xBD, 
  /* RLE: 052 Pixels @ 065,008*/ 52, 0xC0, 0x51, 
  /* RLE: 009 Pixels @ 046,009*/ 9, 0xF7, 0xBD, 
  /* ABS: 002 Pixels @ 055,009*/ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 009 Pixels @ 057,009*/ 9, 0xF7, 0xBD, 
  /* RLE: 050 Pixels @ 066,009*/ 50, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 045,010*/ 7, 0xF7, 0xBD, 
  /* RLE: 008 Pixels @ 052,010*/ 8, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 060,010*/ 7, 0xF7, 0xBD, 
  /* RLE: 049 Pixels @ 067,010*/ 49, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 045,011*/ 6, 0xF7, 0xBD, 
  /* RLE: 010 Pixels @ 051,011*/ 10, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 061,011*/ 6, 0xF7, 0xBD, 
  /* RLE: 049 Pixels @ 067,011*/ 49, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 045,012*/ 5, 0xF7, 0xBD, 
  /* RLE: 012 Pixels @ 050,012*/ 12, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 062,012*/ 5, 0xF7, 0xBD, 
  /* RLE: 007 Pixels @ 067,012*/ 7, 0xC0, 0x51, 
  /* RLE: 047 Pixels @ 003,013*/ 47, 0xF7, 0xBD, 
  /* RLE: 012 Pixels @ 050,013*/ 12, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 062,013*/ 6, 0xF7, 0xBD, 
  /* RLE: 006 Pixels @ 068,013*/ 6, 0xC0, 0x51, 
  /* RLE: 047 Pixels @ 003,014*/ 47, 0xF7, 0xBD, 
  /* RLE: 012 Pixels @ 050,014*/ 12, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 062,014*/ 6, 0xF7, 0xBD, 
  /* RLE: 006 Pixels @ 068,014*/ 6, 0xC0, 0x51, 
  /* RLE: 046 Pixels @ 003,015*/ 46, 0xF7, 0xBD, 
  /* RLE: 014 Pixels @ 049,015*/ 14, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 063,015*/ 5, 0xF7, 0xBD, 
  /* RLE: 006 Pixels @ 068,015*/ 6, 0xC0, 0x51, 
  /* RLE: 046 Pixels @ 003,016*/ 46, 0xF7, 0xBD, 
  /* RLE: 014 Pixels @ 049,016*/ 14, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 063,016*/ 5, 0xF7, 0xBD, 
  /* RLE: 006 Pixels @ 068,016*/ 6, 0xC0, 0x51, 
  /* RLE: 047 Pixels @ 003,017*/ 47, 0xF7, 0xBD, 
  /* RLE: 012 Pixels @ 050,017*/ 12, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 062,017*/ 6, 0xF7, 0xBD, 
  /* RLE: 006 Pixels @ 068,017*/ 6, 0xC0, 0x51, 
  /* RLE: 047 Pixels @ 003,018*/ 47, 0xF7, 0xBD, 
  /* RLE: 012 Pixels @ 050,018*/ 12, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 062,018*/ 6, 0xF7, 0xBD, 
  /* RLE: 006 Pixels @ 068,018*/ 6, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,019*/ 7, 0xF7, 0xBD, 
  /* RLE: 013 Pixels @ 010,019*/ 13, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 023,019*/ 7, 0xF7, 0xBD, 
  /* RLE: 015 Pixels @ 030,019*/ 15, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 045,019*/ 5, 0xF7, 0xBD, 
  /* RLE: 012 Pixels @ 050,019*/ 12, 0xC0, 0x51, 
  /* RLE: 005 Pixels @ 062,019*/ 5, 0xF7, 0xBD, 
  /* RLE: 007 Pixels @ 067,019*/ 7, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,020*/ 7, 0xF7, 0xBD, 
  /* RLE: 013 Pixels @ 010,020*/ 13, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 023,020*/ 7, 0xF7, 0xBD, 
  /* RLE: 015 Pixels @ 030,020*/ 15, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 045,020*/ 6, 0xF7, 0xBD, 
  /* RLE: 010 Pixels @ 051,020*/ 10, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 061,020*/ 6, 0xF7, 0xBD, 
  /* RLE: 007 Pixels @ 067,020*/ 7, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,021*/ 7, 0xF7, 0xBD, 
  /* RLE: 013 Pixels @ 010,021*/ 13, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 023,021*/ 7, 0xF7, 0xBD, 
  /* RLE: 015 Pixels @ 030,021*/ 15, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 045,021*/ 7, 0xF7, 0xBD, 
  /* RLE: 008 Pixels @ 052,021*/ 8, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 060,021*/ 7, 0xF7, 0xBD, 
  /* RLE: 007 Pixels @ 067,021*/ 7, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,022*/ 7, 0xF7, 0xBD, 
  /* RLE: 013 Pixels @ 010,022*/ 13, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 023,022*/ 7, 0xF7, 0xBD, 
  /* RLE: 016 Pixels @ 030,022*/ 16, 0xC0, 0x51, 
  /* RLE: 009 Pixels @ 046,022*/ 9, 0xF7, 0xBD, 
  /* ABS: 002 Pixels @ 055,022*/ 0, 2, 0xC0, 0x51, 0xC0, 0x51, 
  /* RLE: 009 Pixels @ 057,022*/ 9, 0xF7, 0xBD, 
  /* RLE: 008 Pixels @ 066,022*/ 8, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,023*/ 7, 0xF7, 0xBD, 
  /* RLE: 013 Pixels @ 010,023*/ 13, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 023,023*/ 7, 0xF7, 0xBD, 
  /* RLE: 017 Pixels @ 030,023*/ 17, 0xC0, 0x51, 
  /* RLE: 018 Pixels @ 047,023*/ 18, 0xF7, 0xBD, 
  /* RLE: 009 Pixels @ 065,023*/ 9, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,024*/ 7, 0xF7, 0xBD, 
  /* RLE: 013 Pixels @ 010,024*/ 13, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 023,024*/ 7, 0xF7, 0xBD, 
  /* RLE: 018 Pixels @ 030,024*/ 18, 0xC0, 0x51, 
  /* RLE: 016 Pixels @ 048,024*/ 16, 0xF7, 0xBD, 
  /* RLE: 010 Pixels @ 064,024*/ 10, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,025*/ 7, 0xF7, 0xBD, 
  /* RLE: 013 Pixels @ 010,025*/ 13, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 023,025*/ 7, 0xF7, 0xBD, 
  /* RLE: 019 Pixels @ 030,025*/ 19, 0xC0, 0x51, 
  /* RLE: 014 Pixels @ 049,025*/ 14, 0xF7, 0xBD, 
  /* RLE: 011 Pixels @ 063,025*/ 11, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 003,026*/ 7, 0xF7, 0xBD, 
  /* RLE: 013 Pixels @ 010,026*/ 13, 0xC0, 0x51, 
  /* RLE: 007 Pixels @ 023,026*/ 7, 0xF7, 0xBD, 
  /* RLE: 020 Pixels @ 030,026*/ 20, 0xC0, 0x51, 
  /* RLE: 012 Pixels @ 050,026*/ 12, 0xF7, 0xBD, 
  /* RLE: 062 Pixels @ 062,026*/ 62, 0xC0, 0x51, 
  /* RLE: 006 Pixels @ 053,027*/ 6, 0xF7, 0xBD, 
  /* RLE: 296 Pixels @ 059,027*/ 254, 0xC0, 0x51, 42, 0xC0, 0x51, 


  0};  /* 230 for 2272 pixels */

GUI_CONST_STORAGE GUI_BITMAP bmchildlock = {
  71, /* XSize */
  32, /* YSize */
  142, /* BytesPerLine */
  16, /* BitsPerPixel */
  (unsigned char *)acchildlock,  /* Pointer to picture data */
  NULL,  /* Pointer to palette */
  GUI_DRAW_RLE16
};

/* *** End of file *** */
