/******************************************************************************
*  Generated by PSoC Designer 5.1.2306
******************************************************************************/
#include <m8c.h>
// EzI2Cs_1SDA address and mask defines
#pragma	ioport	EzI2Cs_1SDA_Data_ADDR:	0x4
BYTE			EzI2Cs_1SDA_Data_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SDA_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SDA_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SDA_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SDA_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SDA_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SDA_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SDA_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SDA_IntEn_ADDR;
#define EzI2Cs_1SDA_MASK 0x20
// EzI2Cs_1SCL address and mask defines
#pragma	ioport	EzI2Cs_1SCL_Data_ADDR:	0x4
BYTE			EzI2Cs_1SCL_Data_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SCL_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SCL_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SCL_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SCL_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SCL_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SCL_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SCL_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SCL_IntEn_ADDR;
#define EzI2Cs_1SCL_MASK 0x80
// LED_10Pin address and mask defines
#pragma	ioport	LED_10Pin_Data_ADDR:	0x8
BYTE			LED_10Pin_Data_ADDR;
#pragma	ioport	LED_10Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_10Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_10Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_10Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_10Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_10Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_10Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_10Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_10Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_10Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_10Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_10Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_10Pin_IntEn_ADDR:	0x9
BYTE			LED_10Pin_IntEn_ADDR;
#define LED_10Pin_MASK 0x1
// LED_10Pin Shadow defines
//   LED_10Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_10Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED_11Pin address and mask defines
#pragma	ioport	LED_11Pin_Data_ADDR:	0x8
BYTE			LED_11Pin_Data_ADDR;
#pragma	ioport	LED_11Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_11Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_11Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_11Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_11Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_11Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_11Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_11Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_11Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_11Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_11Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_11Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_11Pin_IntEn_ADDR:	0x9
BYTE			LED_11Pin_IntEn_ADDR;
#define LED_11Pin_MASK 0x2
// LED_11Pin Shadow defines
//   LED_11Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_11Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED_12Pin address and mask defines
#pragma	ioport	LED_12Pin_Data_ADDR:	0x8
BYTE			LED_12Pin_Data_ADDR;
#pragma	ioport	LED_12Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_12Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_12Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_12Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_12Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_12Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_12Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_12Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_12Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_12Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_12Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_12Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_12Pin_IntEn_ADDR:	0x9
BYTE			LED_12Pin_IntEn_ADDR;
#define LED_12Pin_MASK 0x4
// LED_12Pin Shadow defines
//   LED_12Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_12Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED_13Pin address and mask defines
#pragma	ioport	LED_13Pin_Data_ADDR:	0x8
BYTE			LED_13Pin_Data_ADDR;
#pragma	ioport	LED_13Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_13Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_13Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_13Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_13Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_13Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_13Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_13Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_13Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_13Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_13Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_13Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_13Pin_IntEn_ADDR:	0x9
BYTE			LED_13Pin_IntEn_ADDR;
#define LED_13Pin_MASK 0x8
// LED_13Pin Shadow defines
//   LED_13Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_13Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED_14Pin address and mask defines
#pragma	ioport	LED_14Pin_Data_ADDR:	0x8
BYTE			LED_14Pin_Data_ADDR;
#pragma	ioport	LED_14Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_14Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_14Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_14Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_14Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_14Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_14Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_14Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_14Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_14Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_14Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_14Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_14Pin_IntEn_ADDR:	0x9
BYTE			LED_14Pin_IntEn_ADDR;
#define LED_14Pin_MASK 0x10
// LED_14Pin Shadow defines
//   LED_14Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_14Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED_15Pin address and mask defines
#pragma	ioport	LED_15Pin_Data_ADDR:	0x8
BYTE			LED_15Pin_Data_ADDR;
#pragma	ioport	LED_15Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_15Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_15Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_15Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_15Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_15Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_15Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_15Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_15Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_15Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_15Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_15Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_15Pin_IntEn_ADDR:	0x9
BYTE			LED_15Pin_IntEn_ADDR;
#define LED_15Pin_MASK 0x20
// LED_15Pin Shadow defines
//   LED_15Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_15Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED_1Pin address and mask defines
#pragma	ioport	LED_1Pin_Data_ADDR:	0x8
BYTE			LED_1Pin_Data_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_1Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_1Pin_IntEn_ADDR:	0x9
BYTE			LED_1Pin_IntEn_ADDR;
#define LED_1Pin_MASK 0x80
// LED_1Pin Shadow defines
//   LED_1Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_1Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
