//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by _Setup.rc
//
#define IDR_MAINFRAME                   101
#define IDR_LICENSEAGREEMENT            102
#define IDR_SLEEP_COM                   103
#define IDR_SETUP_PIF                   104
#define IDD_SETUP_LANGUAGE              111
#define IDD_SETUP_HARDWARE              112
#define IDB_ESPRIT                      113
#define IDB_COMPUTER                    115
#define IDD_SERIAL_NUMBER               116
#define IDD_GET_SERIAL_NUMBER           119
#define IDD_PROGRESS                    120
#define IDD_WELCOME                     123
#define IDD_EXITSUCCESS                 147
#define IDB_SETUP16                     150
#define IDB_SETUP256                    151
#define IDS_APPLICATIONEXE              200
#define IDS_APPLICATIONHLP              201
#define IDS_SETUPEXE                    202
#define IDS_INSTALLEDAPPLICATIONTITLE   210
#define IDS_SETUPAPPLICATIONTITLE       211
#define IDS_INSTALLEDAPPLICATIONSHORTCUT 212
#define IDS_SETUPAPPLICATIONSHORTCUT    213
#define IDS_APPLICATIONSGROUP           214
#define IDS_SUCCESS_MESSAGE             214
#define IDS_PROGRAMFOLDER               215
#define IDS_COMPANYNAME                 216
#define IDS_PROGRAMFILESDIRNAME         220
#define IDS_WIN32SPROGRAMFILESDIRNAME   221
#define IDS_MACPROGRAMFILESDIRNAME      222
#define IDS_WORKGROUPFILESDIRNAME       223
#define IDS_WIN32SWORKGROUPFILESDIRNAME 224
#define IDS_MACWORKGROUPFILESDIRNAME    225
#define IDS_TUTORIALDIRNAME             226
#define IDS_SAMPLESDIRNAME              227
#define IDS_SETUPDIRNAME                228
#define IDS_FLASHMEM_WRITE_ERROR        229
#define IDS_ERR_COMM_PORT_READ          230
#define IDS_COMM_PORT_OPEN              231
#define IDS_ERR_COMM_PORT_NOT_OPEN      232
#define IDS_DOWNLOADING                 233
#define IDS_ERR_FILE_NOT_OPEN           234
#define IDS_ERR_SEND_IMAGE_INFO         235
#define IDS_ERR_UNEXPECTED_PORT_CLOSURE 236
#define IDS_ERR_DOWNLOADING             237
#define IDS_DOWNLOAD_COMPLETE           238
#define IDS_ERR_FILE_HEADER             239
#define IDS_PREPARINGFORUPGRADE         240
#define IDS_INCOMPATIBLE_RELEASE        240
#define IDS_CONFIGURINGSHORTCUTS        241
#define IDS_ERR_HANDSHAKE               241
#define IDS_CONFIGURINGODBC             242
#define IDS_ERR_ACKNWLEDGEMENT          242
#define IDS_CONFIGURINGSETTINGS         243
#define IDS_ERR_WRONG_MESSAGE           243
#define IDS_PLEASEINSERTDISK1           244
#define IDS_ERR_LANG_FILE_NOT_OPEN      244
#define IDS_PLEASERESTORECONNECTION     245
#define IDS_ERR_TRANSMITTING_INFO       245
#define IDS_PLEASEINSERTCDROM           246
#define IDS_ERR_SENDING_CK_SUM          246
#define IDS_NONMAINTSUCCESSMESSAGE      247
#define IDS_INCOMPATIBLE_VERSION        247
#define IDS_MAINTSUCCESSMESSAGE         248
#define IDS_FLASH_BURNING_TIMEOUT       248
#define IDS_INSTALLINGREDISTFILES       249
#define IDS_ERR_INFO_NOT_ACKNOWLEDGED   249
#define IDS_ERR_WRONG_ACK               250
#define IDS_DOWNLOADING_BLOCK           251
#define IDS_ERR_IO                      252
#define IDS_ERR_RESENDING               253
#define IDS_FAILED_SENDING_BLOCK        254
#define IDS_UNDEF_ERROR_MESSAGE         255
#define IDS_VENTILATOR_REPORT           256
#define IDS_WAIT_FOR_BURNING            257
#define IDS_ERR_INIITIAL_SYNC           258
#define IDS_ERR_INITIAL_SYNC            258
#define IDS_ERR_SENDING_REQUEST         259
#define IDS_ERR_COM_PORT_READ           260
#define IDS_ERR_WRONG_REQUEST_MESSAGE   261
#define IDS_ERR_NO_INFO_REQUEST         262
#define IDS_ERR_NO_CK_SUM               263
#define IDS_ERR_INFO_CK_SUM             264
#define IDS_ERR_SENDING_ACK             265
#define IDS_ERR_NO_VENTINFO             266
#define IDS_UNDEFINED_ERROR             267
#define IDS_FLASH_MEM_WRITE_ERROR       268
#define IDS_ERR_CHECKSUM                269
#define IDS_ERR_CRC                     270
#define IDS_BLOCK_NUM_OUTOF_SYNC        271
#define IDS_ERR_FLASH_ERASE             272
#define IDS_FLASH_BURNING               273
#define IDS_ERR_FLASH_TIMEOUT           274
#define IDS_DOWNLOAD_SUCCESS            275
#define IDS_NO_CONNECTION               276
#define IDS_VERIFYING_CONNECTION        277
#define IDS_NO_PORT                     278
#define IDS_CONFIGURATION_ERROR         279
#define IDS_SUCCESSFUL_CONNECTION       280
#define IDS_NO_PORT_HANDLE              281
#define IDS_OPEN_SUCCESS                282
#define IDS_INITIALIZATION_ERROR        283
#define IDS_ERR_BADSYNC                 284
#define IDS_ERR_BADREQUESTACK           285
#define IDS_ERR_SEND_WRITE              286
#define IDS_ERR_SEND_NORESPONSE         287
#define IDS_ERR_SEND_EXCEEDED           288
#define IDS_SEND_OK                     289
#define IDS_ERR_FLASHTIMEOUT            290
#define IDP_SUPPORTEDOS                 500
#define IDP_SETUPABORTED                502
#define IDP_SETUPFAILED                 503
#define IDP_NOTENOUGHDISKSPACE          504
#define IDP_UNKNOWNDISKSPACE            505
#define IDS_ERROR_NOPORT                511
#define IDC_SETUP                       2016
#define IDC_WELCOME                     2035
#define IDC_MESSAGE                     2036
#define IDC_WELCOME1                    2037
#define IDC_WELCOME2                    2038
#define IDC_SUCCEEDED                   2039
#define IDC_PROGDLG_PROGRESS            2040
#define IDC_PROGDLG_PERCENT             2041
#define IDC_PROGDLG_STATUS              2042
#define IDC_COMBO_LANGUAGES             2108
#define IDC_COMBO_COMMPORTS             2109
#define IDC_HARDWARE_STATUS             2110
#define IDC_SN_NOTE                     2112
#define IDC_SERIAL_NUMBER               2116

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2117
#define _APS_NEXT_SYMED_VALUE           600
#endif
#endif
