#ifndef STRINGTABLE_H_
#define STRINGTABLE_H_

/********************************************************************/
/*                                                                  */
/* File Name    : StringTable.h                          			*/
/*                                                                  */
/* General      : StringTable used to keep a list of all the text id*/
/*                 	 						                        */
/*                                                                  */
/* Product Name  : FH310                                            */
/*                                                                  */
/*                                                                  */
/* history                                                          */
/*==================================================================*/
/* [Number]  [Date]            [Editor]            [Explanation]    */
/* -----------+---------------+-------------------+-----------------*/
/*             2016/08/14       Viet Le		  	    new file        */
/* #0001       														*/
/*                                                                  */
/********************************************************************/

//List the Gui event
typedef enum
{
	eNoStringID,
	eTemperatureUnitDataStringID,
	eMeasurementFRDataStringID,
	eO2PercentDataStringID,
	eO2PercentGraphDataStringID,
	eTemperatureCompOrOutletDataStringID,
	ePressure1DataStringID,                                    //(Product tank pressure)
	ePressure2DataStringID,                                    //(Cannula pressure)
	eIlluminanceSensorVoltageStringID,
	eCompPositivePressForceStringID,
	eCompNegativePressForceStringID,
	eChanelSwitchingPressStringID,
	eProductTankMonitorPSAStringId,
	eProductTankMonitorGraphStringId,
	eValve1DataStringId,
	eValve2DataStringId,
	eValve3DataStringId,
	eValve4DataStringId,
	eValve5DataStringId,
	eCompressorRPMDataStringId,
	eCoolingFANDataStringId,
	ePSACycleTimeStringId,
	ePSAParameterDataStringId,
	ePSAParameterDataGraphStringId,
	eFlowRateSettingStringID,
	eFlowRatePSAStringID,
	eMotorRPMFunctionTestStringID,
	ePSAPressureStringID,
	eSolenoid1OnOffSetTimeStringID,
	eSolenoid1OffOffSetTimeStringID,
	eSolenoid2OnOffSetTimeStringID,
	eSolenoid2OffOffSetTimeStringID,
	eSolenoid3OnOffSetTimeStringID,
	eSolenoid3OffOffSetTimeStringID,
	eSolenoid4OnOffSetTimeStringID,
	eSolenoid4OffOffSetTimeStringID,
	eSolenoid5OnOffSetTimeAStringID,
	eSolenoid5OnOffSetTimeBStringID,
	eSolenoid5OpenTimeAStringId,
	eSolenoid5OpenTimeBStringId,
	eCompressorRPMPSAStringId,
	eFCOutputPSAStringId,
	eCoolingFanDutyPSAStringId,
	eMaxPSATimeStringId,
	eSolenoidOpenTimeOnEndStringId,
	//Setting equipment
	eGuidanceVolumeStringId,
	eAlarmVolumeStringId,
	eBuzzerVolumeStringId,
	eRestingFRStringId,
	eExertionFRStringId,
	eBedtimeFRStringId,
	eLCDBrightnessStringId,
	//End Setting equipment
	eCoolingFanFunctiontestStringID,
	eO2ConcentrationTestStringID,
	eFlowRateTestStringID,
	eHighTemperatureStringID,
	eLowTemperatureStringID,
	eLimitOxygenConcentratorStringID,
	eTurnValve1StringID,
	eTurnValve2StringID,
	eTurnValve3StringID,
	eTurnValve4StringID,
	eTurnValve5StringID,
	eTurnLatchingValveStringID,
	eTurnOxygenCylinderStringID,
	eTurnMotorCoolingFANStringID,
	eTurnMotorFilterCleaningStringID,
	eTurnMotorCompressorStringID,
	eTurnBuzzerStringID,
	eTurnAlarmRedLEDStringID,
	eTurnAlarmYellowLEDStringID,
	eTurnLEDPowerAnomaliesStringID,
	eTurnVoiceGuidanceStringID,
	eTurnBackupSystemStringID,
	eTurnOxygenCylinderValueStringID,
	eChildlockStringID,
	eTurnBluetoothStringID,
	eTurnBluetoothTranferStringID,
	eTurnRTCStringID,
	//ON/OFF button
	eOnBtnValve1StringId,
	eOffBtnValve1StringId,
	eOnBtnValve2StringId,
	eOffBtnValve2StringId,
	eOnBtnValve3StringId,
	eOffBtnValve3StringId,
	eOnBtnValve4StringId,
	eOffBtnValve4StringId,
	eOnBtnValve5StringId,
	eOffBtnValve5StringId,
	eOnBtnMotorCoolingStringId,
	eOffBtnMotorCoolingStringId,
	eOnBtnMotorFilterStringId,
	eOffBtnMotorFilterStringId,
	eOnBtnMotorCompressorStringId,
	eOffBtnMotorCompressorStringId,
	eOnBtnBuzzerStringId,
	eOffBtnBuzzerStringId,
	eOnBtnAlarmRedLEDStringId,
	eOffBtnAlarmRedLEDStringId,
	eOnBtnAlarmYellowLEDStringId,
	eOffBtnAlarmYellowLEDStringId,
	eOnBtnPowerLEDStringId,
	eOffBtnPowerLEDStringId,
	eOnBtnVoiceStringId,
	eOffBtnVoiceStringId,
	eOnBtnChildLockStringId,
	eOffBtnChildLockStringId,
	eOnBtnBluetoothStringId,
	eOffBtnBluetoothStringId,
	eOnBtnBluetoothTransferStringId,
	eOffBtnBluetoothTransferStringId,
	eOnBtnRTCStringId,
	eOffBtnRTCStringId,
	//UP/DOWN button
	eUpBtnCoolingStringId,
	eDownBtnCoolingStringId,
	eUpBtnO2ConcentrationTestStringId,
	eDownBtnO2ConcentrationTestStringId,
	eUpBtnFlowRateTestStringId,
	eDownBtnFlowRateTestStringId,
	eUpBtnCompressorStringId,
	eDownBtnCompressorStringId,
	eUpBtnHighTempStringId,
	eDownBtnHighTempStringId,
	eUpBtnLowTempStringId,
	eDownBtnLowTempStringId,
	eUpBtnO2LimitStringId,
	eDownBtnO2LimitStringId,
	eUpBtnFRPSAStringId,
	eDownBtnFRPSAStringId,
	eUpBtnPSAPressureStringId,
	eDownBtnPSAPressureStringId,
	eUpBtnSolenoid1OnOffSetTimeStringId,
	eDownBtnSolenoid1OnOffSetTimeStringId,
	eUpBtnSolenoid1OffOffSetTimeStringId,
	eDownBtnSolenoid1OffOffSetTimeStringId,
	eUpBtnSolenoid2OnOffSetTimeStringId,
	eDownBtnSolenoid2OnOffSetTimeStringId,
	eUpBtnSolenoid2OffOffSetTimeStringId,
	eDownBtnSolenoid2OffOffSetTimeStringId,
	eUpBtnSolenoid3OnOffSetTimeStringId,
	eDownBtnSolenoid3OnOffSetTimeStringId,
	eUpBtnSolenoid3OffOffSetTimeStringId,
	eDownBtnSolenoid3OffOffSetTimeStringId,
	eUpBtnSolenoid4OnOffSetTimeStringId,
	eDownBtnSolenoid4OnOffSetTimeStringId,
	eUpBtnSolenoid4OffOffSetTimeStringId,
	eDownBtnSolenoid4OffOffSetTimeStringId,
	eUpBtnSolenoid5OnOffSetTimeAStringId,
	eDownBtnSolenoid5OnOffSetTimeAStringId,
	eUpBtnSolenoid5OnOffSetTimeBStringId,
	eDownBtnSolenoid5OnOffSetTimeBStringId,
	eUpBtnSolenoid5OpenTimeAStringId,
	eDownBtnSolenoid5OpenTimeAStringId,
	eUpBtnSolenoid5OpenTimeBStringId,
	eDownBtnSolenoid5OpenTimeBStringId,
	eUpBtnCompressorRPMPSAStringId,
	eDownBtnCompressorRPMPSAStringId,
	eUpBtnFCOutputPSAStringId,
	eDownBtnFCOutputPSAStringId,
	eUpBtnCoolingFanDutyPSAStringId,
	eDownBtnCoolingFanDutyPSAStringId,
	eUpBtnMaxPSATimeStringId,
	eDownBtnMaxPSATimeStringId,
	eUpBtnSolenoidOpenTimeOnEndStringId,
	eDownBtnSolenoidOpenTimeOnEndStringId,
	eUpBtnVoiceGuidanceVolumeStringId,
	eDownBtnVoiceGuidanceVolumeStringId,
	eUpBtnAlarmVolumeStringId,
	eDownBtnAlarmVolumeStringId,
	eUpBtnBuzzerVolumeStringId,
	eDownBtnBuzzerVolumeStringId,
	eUpBtnRestingFRStringId,
	eDownBtnRestingFRStringId,
	eUpBtnExertionFRStringId,
	eDownBtnExertionFRStringId,
	eUpBtnBedtimeFRStringId,
	eDownBtnBedtimeFRStringId,
	eUpBtnLCDBrightnessStringId,
	eDownBtnLCDBrightnessStringId,
	//OPEN/CLOSE button
	eOpenBtnLatchingStringId,
	eCloseBtnLatchingStringId,
	//Exist/No button
	eExistBtnStringId,
	eNoExistBtnStringId,
	///////
	eValueOfSettingDutyStringId,
	eValueOfO2ConcentrationTestStringId,
	eValueOfFlowRateTestStringId,
	eValueOfSettingRPMStringId,
	eValueOfValve1StringId,
	eValueOfValve2StringId,
	eValueOfValve3StringId,
	eValueOfValve4StringId,
	eValueOfValve5StringId,
	eValueOfMotorCoolingStringId,
	eValueOfMotorFilterStringId,
	eValueOfMotorCompressorStringId,
	eValueOfBuzzerStringId,
	eValueOfRedLedStringId,
	eValueOfYellowLedStringId,
	eValueOfPowerLedStringId,
	eValueOfVoiceStringId,
	eValueOfLatchingValveStringId,
	eValueOfHighTempStringId,
	eValueOfLowTempStringId,
	eValueOfO2LimitTempStringId,
	eValueOfFRPSAStringId,
	eValueOfPSAPressureStringId,
	eValueOfSolenoid1OnOffSetTimeStringId,
	eValueOfSolenoid1OffOffSetTimeStringId,
	eValueOfSolenoid2OnOffSetTimeStringId,
	eValueOfSolenoid2OffOffSetTimeStringId,
	eValueOfSolenoid3OnOffSetTimeStringId,
	eValueOfSolenoid3OffOffSetTimeStringId,
	eValueOfSolenoid4OnOffSetTimeStringId,
	eValueOfSolenoid4OffOffSetTimeStringId,
	eValueOfSolenoid5OnOffSetTimeAStringId,
	eValueOfSolenoid5OnOffSetTimeBStringId,
	eValueOfSolenoid5OpenTimeAStringId,
	eValueOfSolenoid5OpenTimeBStringId,
	eValueOfCompressorRPMPSAStringId,
	eValueOfFCOutputPSAStringId,
	eValueOfCoolingFanDutyPSAStringId,
	eValueOfMaxPSATimeStringId,
	eValueOfSolenoidOpenTimeOnEndStringId,
	eValueOfGuidanceVolumeStringId,
	eValueOfAlarmVolumeStringId,
	eValueOfBuzzerVolumeStringId,
	eValueOfRestingFRStringId,
	eValueOfExertionFRStringId,
	eValueOfBedtimeFRStringId,
	eValueOfLCDBrightnessStringId,
	eValueOfChildLockStringId,
	eValueOfBluetoothStringId,
	eValueOfBluetoothTransferStringId,
	eValueOfRTCStringId,
	//UNIT
	eUnitLPMStringId,
	eUnitLPMinStringId,
	eUnitVoltageStringId,
	eUnitSecStringId,
	eUnitkPaStringId,
	eUnitPercentStringId,
	eUnitRPMStringId,
	eUnitTemperatureStringId,
	eUnitHighTemperatureStringId,
	eUnitLowTemperatureStringId,
	eUnitLimitO2StringId,
	//OTHER
	eNexBtnPageTwoStringId,
	eNexBtnPageThreeStringId,
	ePrevBtnPageThreeStringId,
	ePrevBtnPageFourStringId,
	eBackBtnFunctionTestPageOneStringId,
	eBackBtnFunctionTestPageTwoStringId,
	eBackBtnFunctionTestPageThreeStringId,
	eBackBtnFunctionTestPageFourStringId,
	eHomeBtnFunctionTestPageOneStringId,
	eHomeBtnFunctionTestPageTwoStringId,
	eHomeBtnFunctionTestPageThreeStringId,
	eHomeBtnFunctionTestPageFourStringId,
	ePSAParameterBtnStringId,
	eBackBtnPSAParameterStringId,
	eHomeBtnPSAParameterStringId,
	eHomeBtnServiceModeStringId,
	eHomeBtnMaintenanceModeModeStringId,
	eBackBtnMonitorPSAStringId,
	eHomeBtnMonitorPSAStringId,
	ePatientModeButtonTestStringId,
	eStandbyModeButtonTestStringId,
	eLogDataBtnStringId,
	eZeroBtnStringId,
	eOneBtnStringId,
	eTwoBtnStringId,
	eThreeBtnStringId,
	eFourBtnStringId,
	eFineBtnStringId,
	eSixBtnStringId,
	eSevenBtnStringId,
	eEightBtnStringId,
	eNineBtnStringId,
	eEnterPassBtnStringId,
	eClearPassBtnStringId,
	eClosePopUpPassStringId,
	eSerialNumberStringId,
	eSoftwareVersionStringId,
	eCalendarStringId,
	ePatientCumulativeHourStringId,
	eUintCumulativeHourStringId,
	eBackBtnEquipmentInforStringId,
	eHomeBtnEquipmentInforStringId,
	eNexBtnEquipmentInforStringId,
	eBackBtnEquipmentInforExtStringId,
	eHomeBtnEquipmentInforExtStringId,
	ePrevBtnEquipmentInforExtStringId,
	eEquipmentConnectedNameStringId,
	eEquipmentConnectedCommodityCodeStringId,
	eEquipmentConnectedVersionStringId,
	eEquipmentConnectedIDSerialNumberStringId,
	eEquipmentSettingConnectedNameStringId,
	eEquipmentSettingConnectedCommodityCodeStringId,
	eEquipmentSettingConnectedVersionStringId,
	eEquipmentSettingConnectedIDSerialNumberStringId,
	eBackBtnEquipmentSettingStringId,
	eHomeBtnEquipmentSettingStringId,
	eNexBtnEquipmentSettingStringId,
	eClearBtnPatientsCumulativeHoursStringId,
	eValuePatientCumulativeHourStringId,
	eCreateBtnContactStringId,
	eValueEditContactStringID,
	eEquipmentSettingDefaultBtnStringId,
	eBackBtnEquipmentSettingExtStringId,
	eHomeBtnEquipmentSettingExtStringId,
	ePrevBtnEquipmentSettingExtStringId,
	eDeleteExternalRegisterStringId,
	eOkBtnStringId,
	eCancelBtnStringId,
	eTitlePopUpEquipmentSettingStringID,
	eZeroContactBtnStringId,
	eOneContactBtnStringId,
	eTwoContactBtnStringId,
	eThreeContactBtnStringId,
	eFourContactBtnStringId,
	eFineContactBtnStringId,
	eSixContactBtnStringId,
	eSevenContactBtnStringId,
	eEightContactBtnStringId,
	eNineContactBtnStringId,
	eOtherContactBtnStringId,
	eBottomTextAlarmStringId,
	eRoundTextAlarmStringId,
	eContactNumberAlarmStringId,
	eCenterTextContactAlarmStringId,
	eO2CylinderBtnStringId,
	eToptextAlarmStringId,
	eAnypalTextStringId,
	eBackBtnMonitorGraphStringId,
	eHomeBtnMonitorGraphStringId,
	eTitlePSAChangeDialogStringId,
	eDevelopmentSettingBtnStringId,
	eMaxIDStringId
}E_StringID;

//Define package setting
typedef struct
{
	E_StringID ID;//Id of string
	const char* String;//String name
}InitTextDesc;

extern InitTextDesc * StringTables[];

#endif /* STRINGTABLE_H_ */
/* end of file */

