//*****************************************************************************
//*****************************************************************************
//  FILENAME: CS.h
//   Version: 1.2, Updated on 2009/7/10 at 10:45:0                                          
//  Generated by PSoC Designer 5.0.985.0
//
//  DESCRIPTION: CS User Module C Language interface file
//               for the (22/24/26/27/29xxx) PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2005. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  CS_Stop
#pragma fastcall16  CS_Start
#pragma fastcall16  CS_On
#pragma fastcall16  CS_Off
#pragma fastcall16  CS_Switch
#pragma fastcall16  CS_Invert
#pragma fastcall16  CS_GetState


//-------------------------------------------------
// Constants for CS API's.
//-------------------------------------------------
//
#define  CS_ON   1
#define  CS_OFF  0

//-------------------------------------------------
// Prototypes of the CS API.
//-------------------------------------------------
extern void  CS_Start(void);                                     
extern void  CS_Stop(void);                                      
extern void  CS_On(void);                                      
extern void  CS_Off(void);                                      
extern void  CS_Switch(BYTE bSwitch);
extern void  CS_Invert(void);                                         
extern BYTE  CS_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------




