//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_3.h
//   Version: 1.40, Updated on 2011/3/29 at 14:30:41                                          
//  Generated by PSoC Designer 5.1.2110.0
//
//  DESCRIPTION: LED_3 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_3_INCLUDE
#define LED_3_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_3_Stop
#pragma fastcall16  LED_3_Start
#pragma fastcall16  LED_3_On
#pragma fastcall16  LED_3_Off
#pragma fastcall16  LED_3_Switch
#pragma fastcall16  LED_3_Invert
#pragma fastcall16  LED_3_GetState


//-------------------------------------------------
// Constants for LED_3 API's.
//-------------------------------------------------
//
#define  LED_3_ON   1
#define  LED_3_OFF  0

//-------------------------------------------------
// Prototypes of the LED_3 API.
//-------------------------------------------------
extern void  LED_3_Start(void);                                     
extern void  LED_3_Stop(void);                                      
extern void  LED_3_On(void);                                      
extern void  LED_3_Off(void);                                      
extern void  LED_3_Switch(BYTE bSwitch);
extern void  LED_3_Invert(void);                                         
extern BYTE  LED_3_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
