//*****************************************************************************
//*****************************************************************************
//  FILENAME: MOSI.h
//   Version: 1.2, Updated on 2009/7/10 at 10:45:0                                          
//  Generated by PSoC Designer 5.0.985.0
//
//  DESCRIPTION: MOSI User Module C Language interface file
//               for the (22/24/26/27/29xxx) PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2005. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  MOSI_Stop
#pragma fastcall16  MOSI_Start
#pragma fastcall16  MOSI_On
#pragma fastcall16  MOSI_Off
#pragma fastcall16  MOSI_Switch
#pragma fastcall16  MOSI_Invert
#pragma fastcall16  MOSI_GetState


//-------------------------------------------------
// Constants for MOSI API's.
//-------------------------------------------------
//
#define  MOSI_ON   1
#define  MOSI_OFF  0

//-------------------------------------------------
// Prototypes of the MOSI API.
//-------------------------------------------------
extern void  MOSI_Start(void);                                     
extern void  MOSI_Stop(void);                                      
extern void  MOSI_On(void);                                      
extern void  MOSI_Off(void);                                      
extern void  MOSI_Switch(BYTE bSwitch);
extern void  MOSI_Invert(void);                                         
extern BYTE  MOSI_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------




