/******************************************************************************
*  Generated by PSoC Designer 5.1.2306
******************************************************************************/
#include <m8c.h>
// AnalogColumn_InputMUX_1 address and mask defines
#pragma	ioport	AnalogColumn_InputMUX_1_Data_ADDR:	0x0
BYTE			AnalogColumn_InputMUX_1_Data_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_DriveMode_0_ADDR:	0x100
BYTE			AnalogColumn_InputMUX_1_DriveMode_0_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_DriveMode_1_ADDR:	0x101
BYTE			AnalogColumn_InputMUX_1_DriveMode_1_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_DriveMode_2_ADDR:	0x3
BYTE			AnalogColumn_InputMUX_1_DriveMode_2_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_GlobalSelect_ADDR:	0x2
BYTE			AnalogColumn_InputMUX_1_GlobalSelect_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_IntCtrl_0_ADDR:	0x102
BYTE			AnalogColumn_InputMUX_1_IntCtrl_0_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_IntCtrl_1_ADDR:	0x103
BYTE			AnalogColumn_InputMUX_1_IntCtrl_1_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_1_IntEn_ADDR:	0x1
BYTE			AnalogColumn_InputMUX_1_IntEn_ADDR;
#define AnalogColumn_InputMUX_1_MASK 0x1
// AnalogColumn_InputMUX_1 Shadow defines
//   AnalogColumn_InputMUX_1_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define AnalogColumn_InputMUX_1_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// AnalogOutBuf_3 address and mask defines
#pragma	ioport	AnalogOutBuf_3_Data_ADDR:	0x0
BYTE			AnalogOutBuf_3_Data_ADDR;
#pragma	ioport	AnalogOutBuf_3_DriveMode_0_ADDR:	0x100
BYTE			AnalogOutBuf_3_DriveMode_0_ADDR;
#pragma	ioport	AnalogOutBuf_3_DriveMode_1_ADDR:	0x101
BYTE			AnalogOutBuf_3_DriveMode_1_ADDR;
#pragma	ioport	AnalogOutBuf_3_DriveMode_2_ADDR:	0x3
BYTE			AnalogOutBuf_3_DriveMode_2_ADDR;
#pragma	ioport	AnalogOutBuf_3_GlobalSelect_ADDR:	0x2
BYTE			AnalogOutBuf_3_GlobalSelect_ADDR;
#pragma	ioport	AnalogOutBuf_3_IntCtrl_0_ADDR:	0x102
BYTE			AnalogOutBuf_3_IntCtrl_0_ADDR;
#pragma	ioport	AnalogOutBuf_3_IntCtrl_1_ADDR:	0x103
BYTE			AnalogOutBuf_3_IntCtrl_1_ADDR;
#pragma	ioport	AnalogOutBuf_3_IntEn_ADDR:	0x1
BYTE			AnalogOutBuf_3_IntEn_ADDR;
#define AnalogOutBuf_3_MASK 0x4
// AnalogOutBuf_3 Shadow defines
//   AnalogOutBuf_3_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define AnalogOutBuf_3_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LED_2Pin address and mask defines
#pragma	ioport	LED_2Pin_Data_ADDR:	0x0
BYTE			LED_2Pin_Data_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_0_ADDR:	0x100
BYTE			LED_2Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_1_ADDR:	0x101
BYTE			LED_2Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_2_ADDR:	0x3
BYTE			LED_2Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_2Pin_GlobalSelect_ADDR:	0x2
BYTE			LED_2Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_2Pin_IntCtrl_0_ADDR:	0x102
BYTE			LED_2Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_2Pin_IntCtrl_1_ADDR:	0x103
BYTE			LED_2Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_2Pin_IntEn_ADDR:	0x1
BYTE			LED_2Pin_IntEn_ADDR;
#define LED_2Pin_MASK 0x80
// LED_2Pin Shadow defines
//   LED_2Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LED_2Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// LED_1Pin address and mask defines
#pragma	ioport	LED_1Pin_Data_ADDR:	0x4
BYTE			LED_1Pin_Data_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_1Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_1Pin_IntEn_ADDR:	0x5
BYTE			LED_1Pin_IntEn_ADDR;
#define LED_1Pin_MASK 0x8
// LED_1Pin Shadow defines
//   LED_1Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_1Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// EzI2Cs_1SDA address and mask defines
#pragma	ioport	EzI2Cs_1SDA_Data_ADDR:	0x4
BYTE			EzI2Cs_1SDA_Data_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SDA_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SDA_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SDA_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SDA_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SDA_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SDA_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SDA_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SDA_IntEn_ADDR;
#define EzI2Cs_1SDA_MASK 0x20
// EzI2Cs_1SDA Shadow defines
//   EzI2Cs_1SDA_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2Cs_1SDA_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// EzI2Cs_1SCL address and mask defines
#pragma	ioport	EzI2Cs_1SCL_Data_ADDR:	0x4
BYTE			EzI2Cs_1SCL_Data_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SCL_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SCL_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SCL_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SCL_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SCL_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SCL_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SCL_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SCL_IntEn_ADDR;
#define EzI2Cs_1SCL_MASK 0x80
// EzI2Cs_1SCL Shadow defines
//   EzI2Cs_1SCL_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2Cs_1SCL_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
