//*****************************************************************************
//*****************************************************************************
//  FILENAME: SCK.h
//   Version: 1.2, Updated on 2009/7/10 at 10:45:0                                          
//  Generated by PSoC Designer 5.0.985.0
//
//  DESCRIPTION: SCK User Module C Language interface file
//               for the (22/24/26/27/29xxx) PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2005. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  SCK_Stop
#pragma fastcall16  SCK_Start
#pragma fastcall16  SCK_On
#pragma fastcall16  SCK_Off
#pragma fastcall16  SCK_Switch
#pragma fastcall16  SCK_Invert
#pragma fastcall16  SCK_GetState


//-------------------------------------------------
// Constants for SCK API's.
//-------------------------------------------------
//
#define  SCK_ON   1
#define  SCK_OFF  0

//-------------------------------------------------
// Prototypes of the SCK API.
//-------------------------------------------------
extern void  SCK_Start(void);                                     
extern void  SCK_Stop(void);                                      
extern void  SCK_On(void);                                      
extern void  SCK_Off(void);                                      
extern void  SCK_Switch(BYTE bSwitch);
extern void  SCK_Invert(void);                                         
extern BYTE  SCK_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------




