/******************************************************************************
*  Generated by PSoC Designer 5.1.2306
******************************************************************************/
#include <m8c.h>
// LED_8Pin address and mask defines
#pragma	ioport	LED_8Pin_Data_ADDR:	0x4
BYTE			LED_8Pin_Data_ADDR;
#pragma	ioport	LED_8Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_8Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_8Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_8Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_8Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_8Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_8Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_8Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_8Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_8Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_8Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_8Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_8Pin_IntEn_ADDR:	0x5
BYTE			LED_8Pin_IntEn_ADDR;
#define LED_8Pin_MASK 0x4
// LED_8Pin Shadow defines
//   LED_8Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_8Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_1Pin address and mask defines
#pragma	ioport	LED_1Pin_Data_ADDR:	0x4
BYTE			LED_1Pin_Data_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_1Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_1Pin_IntEn_ADDR:	0x5
BYTE			LED_1Pin_IntEn_ADDR;
#define LED_1Pin_MASK 0x8
// LED_1Pin Shadow defines
//   LED_1Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_1Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_9Pin address and mask defines
#pragma	ioport	LED_9Pin_Data_ADDR:	0x4
BYTE			LED_9Pin_Data_ADDR;
#pragma	ioport	LED_9Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_9Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_9Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_9Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_9Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_9Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_9Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_9Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_9Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_9Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_9Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_9Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_9Pin_IntEn_ADDR:	0x5
BYTE			LED_9Pin_IntEn_ADDR;
#define LED_9Pin_MASK 0x10
// LED_9Pin Shadow defines
//   LED_9Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_9Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// EzI2Cs_1SDA address and mask defines
#pragma	ioport	EzI2Cs_1SDA_Data_ADDR:	0x4
BYTE			EzI2Cs_1SDA_Data_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SDA_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SDA_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SDA_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SDA_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SDA_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SDA_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SDA_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SDA_IntEn_ADDR;
#define EzI2Cs_1SDA_MASK 0x20
// EzI2Cs_1SDA Shadow defines
//   EzI2Cs_1SDA_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2Cs_1SDA_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// LED_10Pin address and mask defines
#pragma	ioport	LED_10Pin_Data_ADDR:	0x4
BYTE			LED_10Pin_Data_ADDR;
#pragma	ioport	LED_10Pin_DriveMode_0_ADDR:	0x104
BYTE			LED_10Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_10Pin_DriveMode_1_ADDR:	0x105
BYTE			LED_10Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_10Pin_DriveMode_2_ADDR:	0x7
BYTE			LED_10Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_10Pin_GlobalSelect_ADDR:	0x6
BYTE			LED_10Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_10Pin_IntCtrl_0_ADDR:	0x106
BYTE			LED_10Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_10Pin_IntCtrl_1_ADDR:	0x107
BYTE			LED_10Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_10Pin_IntEn_ADDR:	0x5
BYTE			LED_10Pin_IntEn_ADDR;
#define LED_10Pin_MASK 0x40
// LED_10Pin Shadow defines
//   LED_10Pin_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define LED_10Pin_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// EzI2Cs_1SCL address and mask defines
#pragma	ioport	EzI2Cs_1SCL_Data_ADDR:	0x4
BYTE			EzI2Cs_1SCL_Data_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SCL_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SCL_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SCL_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SCL_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SCL_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SCL_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SCL_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SCL_IntEn_ADDR;
#define EzI2Cs_1SCL_MASK 0x80
// EzI2Cs_1SCL Shadow defines
//   EzI2Cs_1SCL_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2Cs_1SCL_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
