/******************************************************************************
*  Generated by PSoC Designer 5.1.2306
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "EzI2Cs_1.h"
#include "LED_1.h"
#include "LED_10.h"
#include "LED_8.h"
#include "LED_9.h"
#include "PWM8_1.h"

#endif
