/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.16                       *
*        Compiled Jun  4 2012, 15:48:50                              *
*        (C) 1998 - 2011 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontEng3L5B2PP.c                                      *
* Font:        SUDRGIWA-Th                                           *
* Height:      8                                                     *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 8                                             *
* Range disabled: 0000 - FFFF                                        *
* Character enabled:   0x30 (48)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontEng3L5B2PP;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0020[  8] = { /* code 0020, SPACE */
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0021[  8] = { /* code 0021, EXCLAMATION MARK */
  0x00,
  0x28,
  0x28,
  0x28,
  0x28,
  0x2C,
  0x00,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0022[  8] = { /* code 0022, QUOTATION MARK */
  0xBC,
  0xAC,
  0x6C,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0023[ 16] = { /* code 0023, NUMBER SIGN */
  0x16, 0x80,
  0x16, 0x80,
  0x7F, 0xD0,
  0x27, 0x40,
  0xBF, 0xC0,
  0x27, 0x00,
  0x27, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0024[ 16] = { /* code 0024, DOLLAR SIGN */
  0x0D, 0x00,
  0x3F, 0x80,
  0x3D, 0x00,
  0x1F, 0x40,
  0x0F, 0xF0,
  0x0C, 0x70,
  0x7F, 0xD0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0025[ 16] = { /* code 0025, PERCENT SIGN */
  0x00, 0x34,
  0x3E, 0xA0,
  0x77, 0xD0,
  0x3F, 0x80,
  0x03, 0x7F,
  0x07, 0xB7,
  0x0D, 0x3F,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0026[ 16] = { /* code 0026, AMPERSAND */
  0x0F, 0xD0,
  0x28, 0xA0,
  0x1F, 0xC0,
  0x3D, 0x70,
  0x62, 0xE0,
  0x3F, 0xF4,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0027[  8] = { /* code 0027, APOSTROPHE */
  0xB0,
  0xB0,
  0x70,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0028[  8] = { /* code 0028, LEFT PARENTHESIS */
  0x1D,
  0x28,
  0x34,
  0x34,
  0x34,
  0x34,
  0x28,
  0x1D
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0029[  8] = { /* code 0029, RIGHT PARENTHESIS */
  0x74,
  0x1C,
  0x0A,
  0x07,
  0x07,
  0x0A,
  0x1C,
  0xB4
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_002A[ 16] = { /* code 002A, ASTERISK */
  0x0D, 0x00,
  0x7F, 0x80,
  0x27, 0x40,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_002B[ 16] = { /* code 002B, PLUS SIGN */
  0x00, 0x00,
  0x07, 0x00,
  0x07, 0x00,
  0x3F, 0xE0,
  0x07, 0x00,
  0x07, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_002C[  8] = { /* code 002C, COMMA */
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0x38,
  0x70
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_002D[  8] = { /* code 002D, HYPHEN-MINUS */
  0x00,
  0x00,
  0x00,
  0x00,
  0xFC,
  0x00,
  0x00,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_002E[  8] = { /* code 002E, FULL STOP */
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0x74,
  0x00,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_002F[ 16] = { /* code 002F, SOLIDUS */
  0x00, 0x00,
  0x07, 0x40,
  0x0A, 0x00,
  0x1C, 0x00,
  0x34, 0x00,
  0xB0, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0030[ 16] = { /* code 0030, DIGIT ZERO */
  0x00, 0x00,
  0x2F, 0xD0,
  0x74, 0xB0,
  0x70, 0x70,
  0x70, 0x70,
  0x74, 0xB0,
  0x2F, 0xD0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0031[ 16] = { /* code 0031, DIGIT ONE */
  0x00, 0x00,
  0x0F, 0x40,
  0x27, 0x40,
  0x03, 0x40,
  0x03, 0x40,
  0x03, 0x40,
  0x03, 0x40,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0032[ 16] = { /* code 0032, DIGIT TWO */
  0x7F, 0xD0,
  0x00, 0xE0,
  0x00, 0xD0,
  0x03, 0xC0,
  0x0F, 0x00,
  0x7F, 0xD0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0033[ 16] = { /* code 0033, DIGIT THREE */
  0x00, 0x00,
  0x7F, 0xD0,
  0x60, 0xA0,
  0x2F, 0xC0,
  0x00, 0xA0,
  0x00, 0xB0,
  0xBF, 0xD0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0034[ 16] = { /* code 0034, DIGIT FOUR */
  0x01, 0xD0,
  0x03, 0xD0,
  0x0D, 0xD0,
  0x24, 0xD0,
  0x3F, 0xF0,
  0x60, 0xD0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0035[ 16] = { /* code 0035, DIGIT FIVE */
  0x00, 0x00,
  0x3F, 0xC0,
  0x34, 0x00,
  0x34, 0x00,
  0x3F, 0xE0,
  0x00, 0x70,
  0x7F, 0xD0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0036[ 16] = { /* code 0036, DIGIT SIX */
  0x00, 0x00,
  0x1F, 0xC0,
  0x34, 0x00,
  0x7F, 0xD0,
  0x74, 0x70,
  0x74, 0x70,
  0x2F, 0xD0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  0x00, 0x00,
  0x7F, 0xD0,
  0x01, 0xC0,
  0x03, 0x40,
  0x07, 0x00,
  0x0E, 0x00,
  0x1C, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  0x2F, 0xD0,
  0x34, 0xB0,
  0x38, 0xD0,
  0x2F, 0xD0,
  0x70, 0xB0,
  0x3F, 0xE0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0039[ 16] = { /* code 0039, DIGIT NINE */
  0x00, 0x00,
  0x3F, 0xD0,
  0x70, 0xB0,
  0x3F, 0xF0,
  0x00, 0xF0,
  0x02, 0xE0,
  0x7F, 0xC0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_003A[  8] = { /* code 003A, COLON */
  0x00,
  0x00,
  0x74,
  0x00,
  0x00,
  0x74,
  0x00,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_003B[  8] = { /* code 003B, SEMICOLON */
  0x00,
  0x00,
  0x74,
  0x00,
  0x00,
  0x00,
  0x38,
  0x70
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_003C[ 16] = { /* code 003C, LESS-THAN SIGN */
  0x00, 0x00,
  0x00, 0x00,
  0x07, 0xC0,
  0x7E, 0x00,
  0xBD, 0x00,
  0x0B, 0xC0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_003D[ 16] = { /* code 003D, EQUALS SIGN */
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0xBF, 0xC0,
  0xBF, 0xC0,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_003E[ 16] = { /* code 003E, GREATER-THAN SIGN */
  0x00, 0x00,
  0x00, 0x00,
  0xB4, 0x00,
  0x1F, 0x40,
  0x0F, 0xC0,
  0xB8, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_003F[ 16] = { /* code 003F, QUESTION MARK */
  0x00, 0x00,
  0x7F, 0x80,
  0x61, 0xC0,
  0x03, 0x80,
  0x0F, 0x00,
  0x1D, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0040[ 16] = { /* code 0040, COMMERCIAL AT */
  0x00, 0x00,
  0x0B, 0xFC,
  0x3F, 0xEB,
  0x7D, 0x97,
  0x6B, 0xFD,
  0x34, 0x00,
  0x0F, 0xF4,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  0x0B, 0x00,
  0x0F, 0x40,
  0x16, 0x80,
  0x20, 0xD0,
  0x3F, 0xE0,
  0x70, 0x70,
  0xE0, 0x30,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  0x00, 0x00,
  0x3F, 0xD0,
  0x34, 0x60,
  0x3F, 0xD0,
  0x34, 0x70,
  0x3F, 0xF0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  0x00, 0x00,
  0x1F, 0xC0,
  0x78, 0x50,
  0x70, 0x00,
  0x74, 0x00,
  0x1F, 0xD0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  0x00, 0x00,
  0x3F, 0xD0,
  0x34, 0x70,
  0x34, 0x30,
  0x34, 0x70,
  0x3F, 0xE0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0045[ 16] = { /* code 0045, LATIN CAPITAL LETTER E */
  0x00, 0x00,
  0x3F, 0xD0,
  0x34, 0x00,
  0x3F, 0xD0,
  0x34, 0x00,
  0x3F, 0xD0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  0x00, 0x00,
  0x2F, 0xD0,
  0x38, 0x00,
  0x3F, 0xD0,
  0x38, 0x00,
  0x38, 0x00,
  0x38, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0047[ 16] = { /* code 0047, LATIN CAPITAL LETTER G */
  0x0B, 0xF8,
  0x3C, 0x00,
  0x74, 0x00,
  0x70, 0xFC,
  0x74, 0x1C,
  0x2C, 0x1C,
  0x0B, 0xF8,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0048[ 16] = { /* code 0048, LATIN CAPITAL LETTER H */
  0x34, 0x28,
  0x34, 0x28,
  0x34, 0x28,
  0x3F, 0xF8,
  0x34, 0x28,
  0x34, 0x28,
  0x34, 0x28,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0049[  8] = { /* code 0049, LATIN CAPITAL LETTER I */
  0x00,
  0x28,
  0x28,
  0x28,
  0x28,
  0x28,
  0x28,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_004A[  8] = { /* code 004A, LATIN CAPITAL LETTER J */
  0x00,
  0x0A,
  0x0A,
  0x0A,
  0x0A,
  0x0A,
  0x7D,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_004B[ 16] = { /* code 004B, LATIN CAPITAL LETTER K */
  0x00, 0x00,
  0x30, 0xE0,
  0x3B, 0x80,
  0x3D, 0x00,
  0x3F, 0x00,
  0x37, 0xC0,
  0x30, 0xF0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  0x34, 0x00,
  0x34, 0x00,
  0x34, 0x00,
  0x34, 0x00,
  0x34, 0x00,
  0x3F, 0xC0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_004D[ 16] = { /* code 004D, LATIN CAPITAL LETTER M */
  0x00, 0x00,
  0x34, 0x0F,
  0x3C, 0x1F,
  0x2D, 0x3B,
  0x27, 0xA7,
  0x23, 0xD7,
  0x21, 0x87,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_004E[ 16] = { /* code 004E, LATIN CAPITAL LETTER N */
  0x00, 0x00,
  0x38, 0x28,
  0x3E, 0x28,
  0x37, 0x68,
  0x31, 0xF8,
  0x30, 0xB8,
  0x30, 0x38,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_004F[ 16] = { /* code 004F, LATIN CAPITAL LETTER O */
  0x00, 0x00,
  0x1F, 0xF0,
  0x38, 0x3C,
  0x70, 0x1C,
  0x70, 0x1C,
  0x38, 0x3C,
  0x1F, 0xF0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  0x00, 0x00,
  0x2F, 0xE0,
  0x38, 0x70,
  0x38, 0x30,
  0x3F, 0xE0,
  0x38, 0x00,
  0x38, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0051[ 16] = { /* code 0051, LATIN CAPITAL LETTER Q */
  0x00, 0x00,
  0x1F, 0xF0,
  0x38, 0x3C,
  0x70, 0x1C,
  0x70, 0x1C,
  0x3A, 0xF8,
  0x1F, 0xF4,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0052[ 16] = { /* code 0052, LATIN CAPITAL LETTER R */
  0x00, 0x00,
  0x3F, 0xE0,
  0x34, 0x70,
  0x3F, 0xD0,
  0x36, 0xC0,
  0x34, 0xD0,
  0x34, 0xB0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0053[ 16] = { /* code 0053, LATIN CAPITAL LETTER S */
  0x00, 0x00,
  0x3F, 0x40,
  0x70, 0x00,
  0x24, 0x00,
  0x1F, 0x80,
  0x01, 0xC0,
  0x7F, 0x80,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  0x00, 0x00,
  0x7F, 0xF0,
  0x07, 0x00,
  0x07, 0x00,
  0x07, 0x00,
  0x07, 0x00,
  0x07, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0055[ 16] = { /* code 0055, LATIN CAPITAL LETTER U */
  0x00, 0x00,
  0x34, 0x28,
  0x34, 0x28,
  0x34, 0x28,
  0x34, 0x28,
  0x2C, 0x38,
  0x0F, 0xF0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0056[ 16] = { /* code 0056, LATIN CAPITAL LETTER V */
  0x00, 0x00,
  0xD0, 0xB0,
  0x60, 0xD0,
  0x35, 0xC0,
  0x2A, 0x80,
  0x1F, 0x40,
  0x0F, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0057[ 24] = { /* code 0057, LATIN CAPITAL LETTER W */
  0x00, 0x00, 0x00,
  0xD1, 0xC2, 0x80,
  0x62, 0xD3, 0x40,
  0x77, 0xA7, 0x00,
  0x3E, 0x3E, 0x00,
  0x2D, 0x3D, 0x00,
  0x1D, 0x2C, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0058[ 16] = { /* code 0058, LATIN CAPITAL LETTER X */
  0x00, 0x00,
  0xB0, 0xE0,
  0x2F, 0xC0,
  0x0F, 0x00,
  0x1F, 0x80,
  0x31, 0xD0,
  0x90, 0xB0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0059[ 16] = { /* code 0059, LATIN CAPITAL LETTER Y */
  0x00, 0x00,
  0x74, 0x70,
  0x2D, 0xD0,
  0x0B, 0x80,
  0x07, 0x00,
  0x07, 0x00,
  0x07, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_005A[ 16] = { /* code 005A, LATIN CAPITAL LETTER Z */
  0x00, 0x00,
  0xBF, 0xD0,
  0x02, 0x40,
  0x0B, 0x00,
  0x2C, 0x00,
  0xBF, 0xC0,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_005B[  8] = { /* code 005B, LEFT SQUARE BRACKET */
  0x2D,
  0x38,
  0x38,
  0x38,
  0x38,
  0x38,
  0x38,
  0x3D
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_005C[ 16] = { /* code 005C, REVERSE SOLIDUS */
  0x70, 0xB0,
  0x28, 0xD0,
  0x0F, 0x80,
  0x07, 0x40,
  0x3F, 0xE0,
  0x07, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_005D[  8] = { /* code 005D, RIGHT SQUARE BRACKET */
  0x2E,
  0x0A,
  0x0A,
  0x0A,
  0x0A,
  0x0A,
  0x0A,
  0x2E
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_005E[ 16] = { /* code 005E, CIRCUMFLEX ACCENT */
  0x1E, 0x00,
  0x3F, 0x40,
  0xA2, 0xC0,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_005F[ 16] = { /* code 005F, LOW LINE */
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0xFF, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0060[ 16] = { /* code 0060, GRAVE ACCENT */
  0x00, 0x00,
  0x3D, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  0x00, 0x00,
  0x00, 0x00,
  0x7F, 0x00,
  0x03, 0x40,
  0x3F, 0x40,
  0x77, 0x40,
  0x7F, 0x40,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  0x60, 0x00,
  0x60, 0x00,
  0x7F, 0xD0,
  0x78, 0xB0,
  0x70, 0x30,
  0x74, 0xB0,
  0x7F, 0xD0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0063[ 16] = { /* code 0063, LATIN SMALL LETTER C */
  0x00, 0x00,
  0x00, 0x00,
  0x2F, 0x40,
  0x74, 0x00,
  0x74, 0x00,
  0x2F, 0x40,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0064[ 16] = { /* code 0064, LATIN SMALL LETTER D */
  0x00, 0xB0,
  0x00, 0xB0,
  0x2F, 0xF0,
  0x74, 0xF0,
  0x70, 0x70,
  0x74, 0xF0,
  0x2F, 0xF0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  0x00, 0x00,
  0x00, 0x00,
  0x2F, 0x40,
  0x71, 0xC0,
  0xBF, 0xC0,
  0x70, 0x00,
  0x3F, 0x80,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0066[  8] = { /* code 0066, LATIN SMALL LETTER F */
  0x1F,
  0x1C,
  0x7F,
  0x1C,
  0x1C,
  0x1C,
  0x1C,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0067[ 16] = { /* code 0067, LATIN SMALL LETTER G */
  0x00, 0x00,
  0x00, 0x00,
  0x2F, 0xC0,
  0x76, 0xC0,
  0x71, 0xC0,
  0x76, 0xC0,
  0x2F, 0x80,
  0x7F, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0068[ 16] = { /* code 0068, LATIN SMALL LETTER H */
  0x34, 0x00,
  0x34, 0x00,
  0x3F, 0xC0,
  0x38, 0xA0,
  0x34, 0x60,
  0x34, 0x60,
  0x34, 0x60,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0069[  8] = { /* code 0069, LATIN SMALL LETTER I */
  0x38,
  0x00,
  0x28,
  0x28,
  0x28,
  0x28,
  0x28,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_006A[  8] = { /* code 006A, LATIN SMALL LETTER J */
  0x2C,
  0x00,
  0x28,
  0x28,
  0x28,
  0x28,
  0x28,
  0xF8
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  0x30, 0x00,
  0x30, 0x00,
  0x37, 0x80,
  0x3F, 0x00,
  0x3C, 0x00,
  0x3F, 0x00,
  0x32, 0xC0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_006C[  8] = { /* code 006C, LATIN SMALL LETTER L */
  0x28,
  0x28,
  0x28,
  0x28,
  0x28,
  0x28,
  0x28,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  0x00, 0x00,
  0x00, 0x00,
  0x3F, 0xFE,
  0x35, 0xD7,
  0x31, 0xC7,
  0x31, 0xC7,
  0x31, 0xC7,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  0x00, 0x00,
  0x00, 0x00,
  0x3F, 0xD0,
  0x38, 0xA0,
  0x34, 0x60,
  0x34, 0x60,
  0x34, 0x60,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  0x00, 0x00,
  0x00, 0x00,
  0x2F, 0xD0,
  0x74, 0xB0,
  0x70, 0x70,
  0x74, 0xB0,
  0x2F, 0xD0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  0x00, 0x00,
  0x00, 0x00,
  0x7F, 0xD0,
  0x74, 0xB0,
  0x70, 0x30,
  0x74, 0xB0,
  0x7F, 0xD0,
  0x60, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0071[ 16] = { /* code 0071, LATIN SMALL LETTER Q */
  0x00, 0x00,
  0x00, 0x00,
  0x2F, 0xC0,
  0x76, 0xC0,
  0x71, 0xC0,
  0x76, 0xC0,
  0x2F, 0xC0,
  0x02, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0072[  8] = { /* code 0072, LATIN SMALL LETTER R */
  0x00,
  0x00,
  0x3F,
  0x34,
  0x34,
  0x34,
  0x34,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0073[  8] = { /* code 0073, LATIN SMALL LETTER S */
  0x00,
  0x00,
  0x7F,
  0x70,
  0x3D,
  0x0B,
  0xBF,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0074[  8] = { /* code 0074, LATIN SMALL LETTER T */
  0x00,
  0x1C,
  0x7F,
  0x1C,
  0x1C,
  0x1F,
  0x00,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0075[ 16] = { /* code 0075, LATIN SMALL LETTER U */
  0x00, 0x00,
  0x00, 0x00,
  0x72, 0x80,
  0x72, 0x80,
  0x72, 0x80,
  0x77, 0x80,
  0x3F, 0xC0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0076[ 16] = { /* code 0076, LATIN SMALL LETTER V */
  0x00, 0x00,
  0x00, 0x00,
  0x93, 0x80,
  0x67, 0x40,
  0x3B, 0x00,
  0x2E, 0x00,
  0x1D, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  0x00, 0x00,
  0x00, 0x00,
  0x83, 0x0C,
  0x57, 0x5C,
  0x2E, 0xF8,
  0x3C, 0xF4,
  0x28, 0xB0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  0x00, 0x00,
  0x00, 0x00,
  0x93, 0x40,
  0x3E, 0x00,
  0x1D, 0x00,
  0x3F, 0x00,
  0x93, 0x80,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_0079[ 16] = { /* code 0079, LATIN SMALL LETTER Y */
  0x00, 0x00,
  0x00, 0x00,
  0x93, 0x80,
  0x67, 0x00,
  0x3A, 0x00,
  0x2D, 0x00,
  0x1C, 0x00,
  0xB8, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_007A[ 16] = { /* code 007A, LATIN SMALL LETTER Z */
  0x00, 0x00,
  0x00, 0x00,
  0xBF, 0x40,
  0x09, 0x00,
  0x2C, 0x00,
  0xBF, 0x40,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_007B[ 16] = { /* code 007B, LEFT CURLY BRACKET */
  0x0F, 0x00,
  0x1D, 0x00,
  0x1D, 0x00,
  0x1D, 0x00,
  0x2C, 0x00,
  0x1D, 0x00,
  0x1D, 0x00,
  0x0F, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_007C[ 16] = { /* code 007C, VERTICAL LINE */
  0x00, 0x00,
  0x0A, 0x00,
  0x0A, 0x00,
  0x0A, 0x00,
  0x0A, 0x00,
  0x0A, 0x00,
  0x0A, 0x00,
  0x0A, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_007D[ 16] = { /* code 007D, RIGHT CURLY BRACKET */
  0x1F, 0x00,
  0x07, 0x00,
  0x07, 0x00,
  0x07, 0x00,
  0x03, 0x80,
  0x07, 0x00,
  0x07, 0x00,
  0x1F, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEng3L5B2PP_007E[ 16] = { /* code 007E, TILDE */
  0x3F, 0xE0,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00,
  0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontEng3L5B2PP_CharInfo[95] = {
   {   3,   3,  1, acGUI_FontEng3L5B2PP_0020 } /* code 0020 */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_0021 } /* code 0021 */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_0022 } /* code 0022 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0023 } /* code 0023 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0024 } /* code 0024 */
  ,{   8,   8,  2, acGUI_FontEng3L5B2PP_0025 } /* code 0025 */
  ,{   7,   7,  2, acGUI_FontEng3L5B2PP_0026 } /* code 0026 */
  ,{   2,   2,  1, acGUI_FontEng3L5B2PP_0027 } /* code 0027 */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_0028 } /* code 0028 */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_0029 } /* code 0029 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_002A } /* code 002A */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_002B } /* code 002B */
  ,{   3,   3,  1, acGUI_FontEng3L5B2PP_002C } /* code 002C */
  ,{   3,   3,  1, acGUI_FontEng3L5B2PP_002D } /* code 002D */
  ,{   3,   3,  1, acGUI_FontEng3L5B2PP_002E } /* code 002E */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_002F } /* code 002F */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0030 } /* code 0030 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0031 } /* code 0031 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0032 } /* code 0032 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0033 } /* code 0033 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0034 } /* code 0034 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0035 } /* code 0035 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0036 } /* code 0036 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0037 } /* code 0037 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0038 } /* code 0038 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0039 } /* code 0039 */
  ,{   3,   3,  1, acGUI_FontEng3L5B2PP_003A } /* code 003A */
  ,{   3,   3,  1, acGUI_FontEng3L5B2PP_003B } /* code 003B */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_003C } /* code 003C */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_003D } /* code 003D */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_003E } /* code 003E */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_003F } /* code 003F */
  ,{   8,   8,  2, acGUI_FontEng3L5B2PP_0040 } /* code 0040 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0041 } /* code 0041 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0042 } /* code 0042 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0043 } /* code 0043 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0044 } /* code 0044 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0045 } /* code 0045 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0046 } /* code 0046 */
  ,{   7,   7,  2, acGUI_FontEng3L5B2PP_0047 } /* code 0047 */
  ,{   7,   7,  2, acGUI_FontEng3L5B2PP_0048 } /* code 0048 */
  ,{   3,   3,  1, acGUI_FontEng3L5B2PP_0049 } /* code 0049 */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_004A } /* code 004A */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_004B } /* code 004B */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_004C } /* code 004C */
  ,{   8,   8,  2, acGUI_FontEng3L5B2PP_004D } /* code 004D */
  ,{   7,   7,  2, acGUI_FontEng3L5B2PP_004E } /* code 004E */
  ,{   7,   7,  2, acGUI_FontEng3L5B2PP_004F } /* code 004F */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0050 } /* code 0050 */
  ,{   7,   7,  2, acGUI_FontEng3L5B2PP_0051 } /* code 0051 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0052 } /* code 0052 */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_0053 } /* code 0053 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0054 } /* code 0054 */
  ,{   7,   7,  2, acGUI_FontEng3L5B2PP_0055 } /* code 0055 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0056 } /* code 0056 */
  ,{   9,   9,  3, acGUI_FontEng3L5B2PP_0057 } /* code 0057 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0058 } /* code 0058 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0059 } /* code 0059 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_005A } /* code 005A */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_005B } /* code 005B */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_005C } /* code 005C */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_005D } /* code 005D */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_005E } /* code 005E */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_005F } /* code 005F */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_0060 } /* code 0060 */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_0061 } /* code 0061 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0062 } /* code 0062 */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_0063 } /* code 0063 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0064 } /* code 0064 */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_0065 } /* code 0065 */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_0066 } /* code 0066 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0067 } /* code 0067 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0068 } /* code 0068 */
  ,{   3,   3,  1, acGUI_FontEng3L5B2PP_0069 } /* code 0069 */
  ,{   3,   3,  1, acGUI_FontEng3L5B2PP_006A } /* code 006A */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_006B } /* code 006B */
  ,{   3,   3,  1, acGUI_FontEng3L5B2PP_006C } /* code 006C */
  ,{   8,   8,  2, acGUI_FontEng3L5B2PP_006D } /* code 006D */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_006E } /* code 006E */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_006F } /* code 006F */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0070 } /* code 0070 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0071 } /* code 0071 */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_0072 } /* code 0072 */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_0073 } /* code 0073 */
  ,{   4,   4,  1, acGUI_FontEng3L5B2PP_0074 } /* code 0074 */
  ,{   6,   6,  2, acGUI_FontEng3L5B2PP_0075 } /* code 0075 */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_0076 } /* code 0076 */
  ,{   7,   7,  2, acGUI_FontEng3L5B2PP_0077 } /* code 0077 */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_0078 } /* code 0078 */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_0079 } /* code 0079 */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_007A } /* code 007A */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_007B } /* code 007B */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_007C } /* code 007C */
  ,{   5,   5,  2, acGUI_FontEng3L5B2PP_007D } /* code 007D */
  ,{   7,   7,  2, acGUI_FontEng3L5B2PP_007E } /* code 007E */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontEng3L5B2PP_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontEng3L5B2PP_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontEng3L5B2PP = {
   GUI_FONTTYPE_PROP_AA2 /* type of font    */
  ,8 /* height of font  */
  ,8 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontEng3L5B2PP_Prop1}
  ,7 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,7 /* Height of capital characters */
};

