/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.14                       *
*        Compiled Jan 12 2012, 10:28:44                              *
*        (C) 1998 - 2011 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Special22B.c                                          *
* Font:        SUDRGIWA-Th                                           *
* Height:      35                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 35                                            *
* Pixel index of character 0x6F (111) at 9/11 set to 1               *
* Pixel index of character 0x6F (111) at 8/11 set to 1               *
* Pixel index of character 0x6F (111) at 10/11 set to 1              *
* Pixel index of character 0x6F (111) at 11/11 set to 1              *
* Pixel index of character 0x6F (111) at 13/12 set to 1              *
* Pixel index of character 0x6F (111) at 12/12 set to 1              *
* Pixel index of character 0x6F (111) at 10/12 set to 1              *
* Pixel index of character 0x6F (111) at 9/12 set to 1               *
* Pixel index of character 0x6F (111) at 8/12 set to 1               *
* Pixel index of character 0x6F (111) at 7/12 set to 1               *
* Pixel index of character 0x6F (111) at 6/12 set to 1               *
* Pixel index of character 0x6F (111) at 6/13 set to 1               *
* Pixel index of character 0x6F (111) at 7/13 set to 1               *
* Pixel index of character 0x6F (111) at 9/13 set to 1               *
* Pixel index of character 0x6F (111) at 10/13 set to 1              *
* Pixel index of character 0x6F (111) at 11/13 set to 1              *
* Pixel index of character 0x6F (111) at 12/13 set to 1              *
* Pixel index of character 0x6F (111) at 14/13 set to 1              *
* Pixel index of character 0x6F (111) at 14/13 set to 0              *
* Pixel index of character 0x6F (111) at 13/13 set to 1              *
* Pixel index of character 0x6F (111) at 14/13 set to 1              *
* Pixel index of character 0x6F (111) at 11/12 set to 1              *
* Pixel index of character 0x6F (111) at 8/13 set to 1               *
* Pixel index of character 0x6F (111) at 5/13 set to 1               *
* Pixel index of character 0x6F (111) at 5/14 set to 1               *
* Pixel index of character 0x6F (111) at 5/16 set to 1               *
* Pixel index of character 0x6F (111) at 5/17 set to 1               *
* Pixel index of character 0x6F (111) at 5/18 set to 1               *
* Pixel index of character 0x6F (111) at 5/15 set to 1               *
* Pixel index of character 0x6F (111) at 4/15 set to 1               *
* Pixel index of character 0x6F (111) at 4/17 set to 1               *
* Pixel index of character 0x6F (111) at 4/18 set to 1               *
* Pixel index of character 0x6F (111) at 4/19 set to 1               *
* Pixel index of character 0x6F (111) at 4/21 set to 0               *
* Pixel index of character 0x6F (111) at 4/16 set to 1               *
* Pixel index of character 0x6F (111) at 4/20 set to 1               *
* Pixel index of character 0x6F (111) at 4/21 set to 1               *
* Pixel index of character 0x6F (111) at 5/19 set to 1               *
* Pixel index of character 0x6F (111) at 5/20 set to 1               *
* Pixel index of character 0x6F (111) at 5/21 set to 1               *
* Pixel index of character 0x6F (111) at 5/22 set to 1               *
* Pixel index of character 0x6F (111) at 5/23 set to 0               *
* Pixel index of character 0x6F (111) at 6/23 set to 1               *
* Pixel index of character 0x6F (111) at 5/23 set to 1               *
* Pixel index of character 0x6F (111) at 6/23 set to 0               *
* Pixel index of character 0x6F (111) at 6/21 set to 1               *
* Pixel index of character 0x6F (111) at 6/21 set to 0               *
* Pixel index of character 0x6F (111) at 6/21 set to 1               *
* Pixel index of character 0x6F (111) at 6/19 set to 1               *
* Pixel index of character 0x6F (111) at 6/18 set to 1               *
* Pixel index of character 0x6F (111) at 6/17 set to 1               *
* Pixel index of character 0x6F (111) at 6/16 set to 1               *
* Pixel index of character 0x6F (111) at 6/15 set to 1               *
* Pixel index of character 0x6F (111) at 6/14 set to 1               *
* Pixel index of character 0x6F (111) at 6/20 set to 1               *
* Pixel index of character 0x6F (111) at 6/22 set to 1               *
* Pixel index of character 0x6F (111) at 6/23 set to 1               *
* Pixel index of character 0x6F (111) at 8/24 set to 1               *
* Pixel index of character 0x6F (111) at 10/24 set to 1              *
* Pixel index of character 0x6F (111) at 11/24 set to 1              *
* Pixel index of character 0x6F (111) at 9/24 set to 1               *
* Pixel index of character 0x6F (111) at 7/23 set to 1               *
* Pixel index of character 0x6F (111) at 7/22 set to 1               *
* Pixel index of character 0x6F (111) at 7/21 set to 1               *
* Pixel index of character 0x6F (111) at 7/20 set to 1               *
* Pixel index of character 0x6F (111) at 7/19 set to 1               *
* Pixel index of character 0x6F (111) at 7/18 set to 1               *
* Pixel index of character 0x6F (111) at 7/17 set to 1               *
* Pixel index of character 0x6F (111) at 7/16 set to 1               *
* Pixel index of character 0x6F (111) at 7/15 set to 1               *
* Pixel index of character 0x6F (111) at 7/14 set to 1               *
* Pixel index of character 0x6F (111) at 8/14 set to 1               *
* Pixel index of character 0x6F (111) at 8/16 set to 1               *
* Pixel index of character 0x6F (111) at 8/17 set to 1               *
* Pixel index of character 0x6F (111) at 8/18 set to 1               *
* Pixel index of character 0x6F (111) at 8/19 set to 1               *
* Pixel index of character 0x6F (111) at 8/15 set to 1               *
* Pixel index of character 0x6F (111) at 8/20 set to 1               *
* Pixel index of character 0x6F (111) at 8/21 set to 1               *
* Pixel index of character 0x6F (111) at 8/22 set to 1               *
* Pixel index of character 0x6F (111) at 8/23 set to 1               *
* Pixel index of character 0x6F (111) at 9/22 set to 1               *
* Pixel index of character 0x6F (111) at 9/21 set to 1               *
* Pixel index of character 0x6F (111) at 9/20 set to 1               *
* Pixel index of character 0x6F (111) at 9/19 set to 1               *
* Pixel index of character 0x6F (111) at 9/18 set to 1               *
* Pixel index of character 0x6F (111) at 9/17 set to 1               *
* Pixel index of character 0x6F (111) at 9/16 set to 1               *
* Pixel index of character 0x6F (111) at 9/14 set to 1               *
* Pixel index of character 0x6F (111) at 10/14 set to 1              *
* Pixel index of character 0x6F (111) at 11/14 set to 1              *
* Pixel index of character 0x6F (111) at 11/14 set to 0              *
* Pixel index of character 0x6F (111) at 11/14 set to 1              *
* Pixel index of character 0x6F (111) at 11/14 set to 0              *
* Pixel index of character 0x6F (111) at 12/14 set to 1              *
* Pixel index of character 0x6F (111) at 13/14 set to 1              *
* Pixel index of character 0x6F (111) at 14/14 set to 1              *
* Pixel index of character 0x6F (111) at 11/14 set to 1              *
* Pixel index of character 0x6F (111) at 9/15 set to 1               *
* Pixel index of character 0x6F (111) at 10/15 set to 1              *
* Pixel index of character 0x6F (111) at 12/15 set to 1              *
* Pixel index of character 0x6F (111) at 13/15 set to 1              *
* Pixel index of character 0x6F (111) at 14/15 set to 1              *
* Pixel index of character 0x6F (111) at 15/15 set to 1              *
* Pixel index of character 0x6F (111) at 11/15 set to 1              *
* Pixel index of character 0x6F (111) at 10/16 set to 1              *
* Pixel index of character 0x6F (111) at 10/17 set to 1              *
* Pixel index of character 0x6F (111) at 10/18 set to 1              *
* Pixel index of character 0x6F (111) at 10/19 set to 1              *
* Pixel index of character 0x6F (111) at 10/20 set to 1              *
* Pixel index of character 0x6F (111) at 10/21 set to 1              *
* Pixel index of character 0x6F (111) at 10/22 set to 1              *
* Pixel index of character 0x6F (111) at 10/23 set to 1              *
* Pixel index of character 0x6F (111) at 9/23 set to 1               *
* Pixel index of character 0x6F (111) at 11/23 set to 1              *
* Pixel index of character 0x6F (111) at 12/23 set to 1              *
* Pixel index of character 0x6F (111) at 13/23 set to 1              *
* Pixel index of character 0x6F (111) at 13/22 set to 1              *
* Pixel index of character 0x6F (111) at 13/21 set to 1              *
* Pixel index of character 0x6F (111) at 13/19 set to 1              *
* Pixel index of character 0x6F (111) at 13/18 set to 1              *
* Pixel index of character 0x6F (111) at 13/17 set to 1              *
* Pixel index of character 0x6F (111) at 13/16 set to 1              *
* Pixel index of character 0x6F (111) at 11/16 set to 1              *
* Pixel index of character 0x6F (111) at 10/16 set to 0              *
* Pixel index of character 0x6F (111) at 12/16 set to 1              *
* Pixel index of character 0x6F (111) at 9/16 set to 0               *
* Pixel index of character 0x6F (111) at 10/16 set to 1              *
* Pixel index of character 0x6F (111) at 9/16 set to 1               *
* Pixel index of character 0x6F (111) at 11/18 set to 1              *
* Pixel index of character 0x6F (111) at 11/19 set to 1              *
* Pixel index of character 0x6F (111) at 11/20 set to 1              *
* Pixel index of character 0x6F (111) at 11/21 set to 1              *
* Pixel index of character 0x6F (111) at 11/22 set to 1              *
* Pixel index of character 0x6F (111) at 11/17 set to 1              *
* Pixel index of character 0x6F (111) at 13/17 set to 0              *
* Pixel index of character 0x6F (111) at 13/18 set to 0              *
* Pixel index of character 0x6F (111) at 13/19 set to 0              *
* Pixel index of character 0x6F (111) at 12/19 set to 1              *
* Pixel index of character 0x6F (111) at 12/19 set to 0              *
* Pixel index of character 0x6F (111) at 12/18 set to 1              *
* Pixel index of character 0x6F (111) at 13/18 set to 1              *
* Pixel index of character 0x6F (111) at 14/18 set to 1              *
* Pixel index of character 0x6F (111) at 13/17 set to 1              *
* Pixel index of character 0x6F (111) at 12/17 set to 1              *
* Pixel index of character 0x6F (111) at 12/19 set to 1              *
* Pixel index of character 0x6F (111) at 12/20 set to 1              *
* Pixel index of character 0x6F (111) at 12/21 set to 1              *
* Pixel index of character 0x6F (111) at 12/22 set to 1              *
* Pixel index of character 0x6F (111) at 13/20 set to 1              *
* Pixel index of character 0x6F (111) at 14/20 set to 1              *
* Pixel index of character 0x6F (111) at 15/20 set to 1              *
* Pixel index of character 0x6F (111) at 14/21 set to 1              *
* Pixel index of character 0x6F (111) at 14/22 set to 1              *
* Pixel index of character 0x6F (111) at 13/19 set to 1              *
* Pixel index of character 0x6F (111) at 14/19 set to 1              *
* Pixel index of character 0x6F (111) at 15/19 set to 1              *
* Pixel index of character 0x6F (111) at 15/18 set to 1              *
* Pixel index of character 0x6F (111) at 15/16 set to 1              *
* Pixel index of character 0x6F (111) at 14/16 set to 1              *
* Pixel index of character 0x6F (111) at 14/17 set to 1              *
* Pixel index of character 0x6F (111) at 15/17 set to 1              *
* Range disabled: 0000 - FFFF                                        *
* Character enabled:   0x6F (111)                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSpecial22B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSpecial22B_006F[105] = { /* code 006F, LATIN SMALL LETTER O */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ______XX,XXXXXX__,________,
  ____XXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,________,
  ______XX,XXXXXX__,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSpecial22B_CharInfo[1] = {
   {  20,  20,  3, acGUI_FontSpecial22B_006F } /* code 006F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSpecial22B_Prop1 = {
   0x006F /* first character */
  ,0x006F /* last character  */
  ,&GUI_FontSpecial22B_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSpecial22B = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,35 /* height of font  */
  ,35 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSpecial22B_Prop1}
  ,27 /* Baseline */
  ,17 /* Height of lowercase characters */
  ,23 /* Height of capital characters */
};

