/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.14                       *
*        Compiled Jan 12 2012, 10:28:44                              *
*        (C) 1998 - 2011 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Special32B.c                                          *
* Font:        SUDRGIWA-Th                                           *
* Height:      51                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 51                                            *
* Pixel index of character 0x6F (111) at 14/17 set to 1              *
* Character disabled:  0x6F (111)                                    *
* Character enabled:   0x6F (111)                                    *
* Pixel index of character 0x6F (111) at 16/17 set to 1              *
* Pixel index of character 0x6F (111) at 16/17 set to 0              *
* Pixel index of character 0x6F (111) at 15/19 set to 1              *
* Pixel index of character 0x6F (111) at 17/23 set to 1              *
* Pixel index of character 0x6F (111) at 15/17 set to 1              *
* Pixel index of character 0x6F (111) at 16/17 set to 1              *
* Pixel index of character 0x6F (111) at 16/19 set to 1              *
* Pixel index of character 0x6F (111) at 15/19 set to 0              *
* Pixel index of character 0x6F (111) at 14/19 set to 1              *
* Pixel index of character 0x6F (111) at 14/18 set to 1              *
* Pixel index of character 0x6F (111) at 13/17 set to 1              *
* Pixel index of character 0x6F (111) at 12/17 set to 1              *
* Pixel index of character 0x6F (111) at 11/18 set to 1              *
* Pixel index of character 0x6F (111) at 11/19 set to 1              *
* Pixel index of character 0x6F (111) at 10/20 set to 1              *
* Pixel index of character 0x6F (111) at 9/20 set to 1               *
* Pixel index of character 0x6F (111) at 8/19 set to 0               *
* Pixel index of character 0x6F (111) at 9/19 set to 1               *
* Pixel index of character 0x6F (111) at 10/19 set to 1              *
* Pixel index of character 0x6F (111) at 9/19 set to 0               *
* Pixel index of character 0x6F (111) at 7/19 set to 0               *
* Pixel index of character 0x6F (111) at 7/20 set to 0               *
* Pixel index of character 0x6F (111) at 7/21 set to 0               *
* Pixel index of character 0x6F (111) at 7/22 set to 0               *
* Pixel index of character 0x6F (111) at 7/23 set to 1               *
* Pixel index of character 0x6F (111) at 7/22 set to 1               *
* Pixel index of character 0x6F (111) at 7/20 set to 1               *
* Pixel index of character 0x6F (111) at 7/19 set to 1               *
* Pixel index of character 0x6F (111) at 7/21 set to 1               *
* Pixel index of character 0x6F (111) at 9/19 set to 1               *
* Pixel index of character 0x6F (111) at 8/19 set to 1               *
* Pixel index of character 0x6F (111) at 8/21 set to 1               *
* Pixel index of character 0x6F (111) at 8/23 set to 1               *
* Pixel index of character 0x6F (111) at 8/22 set to 1               *
* Pixel index of character 0x6F (111) at 8/24 set to 1               *
* Pixel index of character 0x6F (111) at 7/24 set to 1               *
* Pixel index of character 0x6F (111) at 7/26 set to 1               *
* Pixel index of character 0x6F (111) at 7/25 set to 1               *
* Pixel index of character 0x6F (111) at 8/25 set to 1               *
* Pixel index of character 0x6F (111) at 8/26 set to 1               *
* Pixel index of character 0x6F (111) at 8/27 set to 1               *
* Pixel index of character 0x6F (111) at 8/28 set to 1               *
* Pixel index of character 0x6F (111) at 7/27 set to 1               *
* Pixel index of character 0x6F (111) at 7/28 set to 1               *
* Pixel index of character 0x6F (111) at 7/29 set to 1               *
* Pixel index of character 0x6F (111) at 8/29 set to 1               *
* Pixel index of character 0x6F (111) at 7/30 set to 1               *
* Pixel index of character 0x6F (111) at 8/30 set to 1               *
* Pixel index of character 0x6F (111) at 8/31 set to 1               *
* Pixel index of character 0x6F (111) at 8/32 set to 1               *
* Pixel index of character 0x6F (111) at 10/32 set to 1              *
* Pixel index of character 0x6F (111) at 12/32 set to 1              *
* Pixel index of character 0x6F (111) at 11/32 set to 1              *
* Pixel index of character 0x6F (111) at 12/31 set to 1              *
* Pixel index of character 0x6F (111) at 12/30 set to 1              *
* Pixel index of character 0x6F (111) at 12/29 set to 1              *
* Pixel index of character 0x6F (111) at 12/28 set to 1              *
* Pixel index of character 0x6F (111) at 12/27 set to 1              *
* Pixel index of character 0x6F (111) at 12/26 set to 1              *
* Pixel index of character 0x6F (111) at 12/25 set to 1              *
* Pixel index of character 0x6F (111) at 12/25 set to 0              *
* Pixel index of character 0x6F (111) at 12/25 set to 1              *
* Pixel index of character 0x6F (111) at 12/25 set to 0              *
* Pixel index of character 0x6F (111) at 12/25 set to 1              *
* Pixel index of character 0x6F (111) at 12/24 set to 1              *
* Pixel index of character 0x6F (111) at 12/24 set to 0              *
* Pixel index of character 0x6F (111) at 12/24 set to 1              *
* Pixel index of character 0x6F (111) at 12/23 set to 1              *
* Pixel index of character 0x6F (111) at 12/23 set to 0              *
* Pixel index of character 0x6F (111) at 12/21 set to 1              *
* Pixel index of character 0x6F (111) at 12/20 set to 1              *
* Pixel index of character 0x6F (111) at 12/19 set to 1              *
* Pixel index of character 0x6F (111) at 12/18 set to 1              *
* Pixel index of character 0x6F (111) at 13/18 set to 1              *
* Pixel index of character 0x6F (111) at 16/18 set to 1              *
* Pixel index of character 0x6F (111) at 17/18 set to 1              *
* Pixel index of character 0x6F (111) at 15/18 set to 1              *
* Pixel index of character 0x6F (111) at 15/20 set to 1              *
* Pixel index of character 0x6F (111) at 15/19 set to 1              *
* Pixel index of character 0x6F (111) at 13/19 set to 1              *
* Pixel index of character 0x6F (111) at 13/20 set to 1              *
* Pixel index of character 0x6F (111) at 14/20 set to 1              *
* Pixel index of character 0x6F (111) at 14/21 set to 1              *
* Pixel index of character 0x6F (111) at 14/23 set to 1              *
* Pixel index of character 0x6F (111) at 14/24 set to 1              *
* Pixel index of character 0x6F (111) at 14/25 set to 1              *
* Pixel index of character 0x6F (111) at 14/26 set to 1              *
* Pixel index of character 0x6F (111) at 14/27 set to 1              *
* Pixel index of character 0x6F (111) at 14/28 set to 1              *
* Pixel index of character 0x6F (111) at 14/29 set to 1              *
* Pixel index of character 0x6F (111) at 14/30 set to 1              *
* Pixel index of character 0x6F (111) at 14/30 set to 0              *
* Pixel index of character 0x6F (111) at 14/30 set to 1              *
* Pixel index of character 0x6F (111) at 14/30 set to 0              *
* Pixel index of character 0x6F (111) at 14/30 set to 1              *
* Pixel index of character 0x6F (111) at 14/32 set to 1              *
* Pixel index of character 0x6F (111) at 14/33 set to 1              *
* Pixel index of character 0x6F (111) at 14/34 set to 1              *
* Pixel index of character 0x6F (111) at 14/35 set to 1              *
* Pixel index of character 0x6F (111) at 15/34 set to 1              *
* Pixel index of character 0x6F (111) at 15/34 set to 0              *
* Pixel index of character 0x6F (111) at 15/32 set to 1              *
* Pixel index of character 0x6F (111) at 15/31 set to 1              *
* Pixel index of character 0x6F (111) at 15/30 set to 1              *
* Pixel index of character 0x6F (111) at 15/29 set to 1              *
* Pixel index of character 0x6F (111) at 15/28 set to 1              *
* Pixel index of character 0x6F (111) at 15/27 set to 1              *
* Pixel index of character 0x6F (111) at 15/26 set to 1              *
* Pixel index of character 0x6F (111) at 15/25 set to 1              *
* Pixel index of character 0x6F (111) at 15/23 set to 1              *
* Pixel index of character 0x6F (111) at 15/22 set to 1              *
* Pixel index of character 0x6F (111) at 15/21 set to 1              *
* Pixel index of character 0x6F (111) at 13/21 set to 1              *
* Pixel index of character 0x6F (111) at 13/22 set to 1              *
* Pixel index of character 0x6F (111) at 14/22 set to 1              *
* Pixel index of character 0x6F (111) at 11/22 set to 1              *
* Pixel index of character 0x6F (111) at 11/20 set to 1              *
* Pixel index of character 0x6F (111) at 11/21 set to 1              *
* Pixel index of character 0x6F (111) at 9/21 set to 1               *
* Pixel index of character 0x6F (111) at 10/21 set to 1              *
* Pixel index of character 0x6F (111) at 10/22 set to 1              *
* Pixel index of character 0x6F (111) at 10/24 set to 1              *
* Pixel index of character 0x6F (111) at 10/25 set to 1              *
* Pixel index of character 0x6F (111) at 10/26 set to 1              *
* Pixel index of character 0x6F (111) at 10/27 set to 1              *
* Pixel index of character 0x6F (111) at 10/28 set to 1              *
* Pixel index of character 0x6F (111) at 10/29 set to 1              *
* Pixel index of character 0x6F (111) at 10/30 set to 1              *
* Pixel index of character 0x6F (111) at 10/32 set to 0              *
* Pixel index of character 0x6F (111) at 9/32 set to 1               *
* Pixel index of character 0x6F (111) at 9/32 set to 0               *
* Pixel index of character 0x6F (111) at 9/32 set to 1               *
* Pixel index of character 0x6F (111) at 9/32 set to 0               *
* Pixel index of character 0x6F (111) at 9/31 set to 1               *
* Pixel index of character 0x6F (111) at 9/31 set to 0               *
* Pixel index of character 0x6F (111) at 9/29 set to 1               *
* Pixel index of character 0x6F (111) at 9/28 set to 1               *
* Pixel index of character 0x6F (111) at 9/27 set to 1               *
* Pixel index of character 0x6F (111) at 9/26 set to 1               *
* Pixel index of character 0x6F (111) at 9/25 set to 1               *
* Pixel index of character 0x6F (111) at 9/24 set to 1               *
* Pixel index of character 0x6F (111) at 9/23 set to 1               *
* Pixel index of character 0x6F (111) at 9/22 set to 1               *
* Pixel index of character 0x6F (111) at 12/22 set to 1              *
* Pixel index of character 0x6F (111) at 13/23 set to 1              *
* Pixel index of character 0x6F (111) at 11/23 set to 1              *
* Pixel index of character 0x6F (111) at 10/23 set to 1              *
* Pixel index of character 0x6F (111) at 12/23 set to 1              *
* Pixel index of character 0x6F (111) at 11/24 set to 1              *
* Pixel index of character 0x6F (111) at 11/25 set to 1              *
* Pixel index of character 0x6F (111) at 11/26 set to 1              *
* Pixel index of character 0x6F (111) at 11/27 set to 1              *
* Pixel index of character 0x6F (111) at 11/28 set to 1              *
* Pixel index of character 0x6F (111) at 11/29 set to 1              *
* Pixel index of character 0x6F (111) at 11/30 set to 1              *
* Pixel index of character 0x6F (111) at 11/31 set to 1              *
* Pixel index of character 0x6F (111) at 11/31 set to 0              *
* Pixel index of character 0x6F (111) at 10/31 set to 1              *
* Pixel index of character 0x6F (111) at 11/31 set to 1              *
* Pixel index of character 0x6F (111) at 9/31 set to 1               *
* Pixel index of character 0x6F (111) at 9/30 set to 1               *
* Pixel index of character 0x6F (111) at 9/33 set to 1               *
* Pixel index of character 0x6F (111) at 9/32 set to 1               *
* Pixel index of character 0x6F (111) at 10/32 set to 1              *
* Pixel index of character 0x6F (111) at 10/33 set to 1              *
* Pixel index of character 0x6F (111) at 10/34 set to 1              *
* Pixel index of character 0x6F (111) at 11/34 set to 1              *
* Pixel index of character 0x6F (111) at 11/33 set to 1              *
* Pixel index of character 0x6F (111) at 12/33 set to 1              *
* Pixel index of character 0x6F (111) at 13/33 set to 1              *
* Pixel index of character 0x6F (111) at 13/32 set to 1              *
* Pixel index of character 0x6F (111) at 13/31 set to 1              *
* Pixel index of character 0x6F (111) at 13/30 set to 1              *
* Pixel index of character 0x6F (111) at 13/29 set to 1              *
* Pixel index of character 0x6F (111) at 13/28 set to 1              *
* Pixel index of character 0x6F (111) at 13/27 set to 1              *
* Pixel index of character 0x6F (111) at 13/26 set to 1              *
* Pixel index of character 0x6F (111) at 13/24 set to 1              *
* Pixel index of character 0x6F (111) at 13/25 set to 1              *
* Pixel index of character 0x6F (111) at 15/24 set to 1              *
* Pixel index of character 0x6F (111) at 14/31 set to 1              *
* Pixel index of character 0x6F (111) at 13/34 set to 1              *
* Pixel index of character 0x6F (111) at 11/34 set to 0              *
* Pixel index of character 0x6F (111) at 11/35 set to 1              *
* Pixel index of character 0x6F (111) at 11/34 set to 1              *
* Pixel index of character 0x6F (111) at 12/34 set to 1              *
* Pixel index of character 0x6F (111) at 12/35 set to 1              *
* Pixel index of character 0x6F (111) at 12/36 set to 1              *
* Pixel index of character 0x6F (111) at 13/36 set to 1              *
* Pixel index of character 0x6F (111) at 13/35 set to 1              *
* Pixel index of character 0x6F (111) at 14/36 set to 1              *
* Pixel index of character 0x6F (111) at 15/36 set to 1              *
* Pixel index of character 0x6F (111) at 15/35 set to 1              *
* Pixel index of character 0x6F (111) at 15/33 set to 1              *
* Pixel index of character 0x6F (111) at 15/34 set to 1              *
* Pixel index of character 0x6F (111) at 16/36 set to 1              *
* Pixel index of character 0x6F (111) at 16/35 set to 1              *
* Pixel index of character 0x6F (111) at 16/34 set to 1              *
* Pixel index of character 0x6F (111) at 16/33 set to 1              *
* Pixel index of character 0x6F (111) at 16/32 set to 1              *
* Pixel index of character 0x6F (111) at 16/31 set to 1              *
* Pixel index of character 0x6F (111) at 16/30 set to 1              *
* Pixel index of character 0x6F (111) at 16/29 set to 1              *
* Pixel index of character 0x6F (111) at 16/28 set to 1              *
* Pixel index of character 0x6F (111) at 16/26 set to 1              *
* Pixel index of character 0x6F (111) at 16/25 set to 1              *
* Pixel index of character 0x6F (111) at 16/24 set to 1              *
* Pixel index of character 0x6F (111) at 16/22 set to 1              *
* Pixel index of character 0x6F (111) at 16/21 set to 1              *
* Pixel index of character 0x6F (111) at 16/20 set to 1              *
* Pixel index of character 0x6F (111) at 17/19 set to 1              *
* Pixel index of character 0x6F (111) at 18/19 set to 1              *
* Pixel index of character 0x6F (111) at 17/20 set to 1              *
* Pixel index of character 0x6F (111) at 17/22 set to 1              *
* Pixel index of character 0x6F (111) at 17/21 set to 1              *
* Pixel index of character 0x6F (111) at 16/23 set to 1              *
* Pixel index of character 0x6F (111) at 16/27 set to 1              *
* Pixel index of character 0x6F (111) at 17/35 set to 1              *
* Pixel index of character 0x6F (111) at 17/34 set to 1              *
* Pixel index of character 0x6F (111) at 17/33 set to 1              *
* Pixel index of character 0x6F (111) at 17/32 set to 1              *
* Pixel index of character 0x6F (111) at 17/31 set to 1              *
* Pixel index of character 0x6F (111) at 17/29 set to 1              *
* Pixel index of character 0x6F (111) at 17/28 set to 1              *
* Pixel index of character 0x6F (111) at 17/27 set to 1              *
* Pixel index of character 0x6F (111) at 17/26 set to 1              *
* Pixel index of character 0x6F (111) at 17/25 set to 1              *
* Pixel index of character 0x6F (111) at 17/24 set to 1              *
* Pixel index of character 0x6F (111) at 17/24 set to 0              *
* Pixel index of character 0x6F (111) at 17/30 set to 1              *
* Pixel index of character 0x6F (111) at 17/24 set to 1              *
* Pixel index of character 0x6F (111) at 18/20 set to 1              *
* Pixel index of character 0x6F (111) at 18/22 set to 1              *
* Pixel index of character 0x6F (111) at 18/23 set to 1              *
* Pixel index of character 0x6F (111) at 18/24 set to 1              *
* Pixel index of character 0x6F (111) at 18/21 set to 1              *
* Pixel index of character 0x6F (111) at 18/26 set to 1              *
* Pixel index of character 0x6F (111) at 18/28 set to 1              *
* Pixel index of character 0x6F (111) at 18/29 set to 1              *
* Pixel index of character 0x6F (111) at 18/30 set to 1              *
* Pixel index of character 0x6F (111) at 18/31 set to 1              *
* Pixel index of character 0x6F (111) at 18/33 set to 1              *
* Pixel index of character 0x6F (111) at 18/34 set to 1              *
* Pixel index of character 0x6F (111) at 18/35 set to 0              *
* Pixel index of character 0x6F (111) at 18/33 set to 0              *
* Pixel index of character 0x6F (111) at 18/32 set to 1              *
* Pixel index of character 0x6F (111) at 18/31 set to 0              *
* Pixel index of character 0x6F (111) at 18/31 set to 1              *
* Pixel index of character 0x6F (111) at 18/27 set to 1              *
* Pixel index of character 0x6F (111) at 18/25 set to 1              *
* Pixel index of character 0x6F (111) at 18/33 set to 1              *
* Pixel index of character 0x6F (111) at 18/35 set to 1              *
* Pixel index of character 0x6F (111) at 19/33 set to 1              *
* Pixel index of character 0x6F (111) at 19/32 set to 1              *
* Pixel index of character 0x6F (111) at 19/31 set to 1              *
* Pixel index of character 0x6F (111) at 19/30 set to 1              *
* Pixel index of character 0x6F (111) at 19/29 set to 1              *
* Pixel index of character 0x6F (111) at 19/28 set to 1              *
* Pixel index of character 0x6F (111) at 19/27 set to 1              *
* Pixel index of character 0x6F (111) at 19/26 set to 1              *
* Pixel index of character 0x6F (111) at 19/25 set to 1              *
* Pixel index of character 0x6F (111) at 19/24 set to 1              *
* Pixel index of character 0x6F (111) at 19/23 set to 1              *
* Pixel index of character 0x6F (111) at 19/22 set to 1              *
* Pixel index of character 0x6F (111) at 19/22 set to 0              *
* Pixel index of character 0x6F (111) at 19/21 set to 1              *
* Pixel index of character 0x6F (111) at 19/20 set to 1              *
* Pixel index of character 0x6F (111) at 19/22 set to 1              *
* Pixel index of character 0x6F (111) at 20/21 set to 1              *
* Pixel index of character 0x6F (111) at 20/22 set to 1              *
* Pixel index of character 0x6F (111) at 20/23 set to 1              *
* Pixel index of character 0x6F (111) at 20/24 set to 1              *
* Pixel index of character 0x6F (111) at 20/25 set to 1              *
* Pixel index of character 0x6F (111) at 20/26 set to 1              *
* Pixel index of character 0x6F (111) at 20/28 set to 1              *
* Pixel index of character 0x6F (111) at 20/29 set to 1              *
* Pixel index of character 0x6F (111) at 20/30 set to 1              *
* Pixel index of character 0x6F (111) at 20/27 set to 1              *
* Pixel index of character 0x6F (111) at 20/31 set to 1              *
* Pixel index of character 0x6F (111) at 20/32 set to 1              *
* Pixel index of character 0x6F (111) at 21/30 set to 1              *
* Pixel index of character 0x6F (111) at 21/29 set to 1              *
* Pixel index of character 0x6F (111) at 21/28 set to 1              *
* Pixel index of character 0x6F (111) at 21/27 set to 1              *
* Pixel index of character 0x6F (111) at 21/26 set to 1              *
* Pixel index of character 0x6F (111) at 21/24 set to 1              *
* Pixel index of character 0x6F (111) at 21/23 set to 1              *
* Pixel index of character 0x6F (111) at 21/23 set to 0              *
* Pixel index of character 0x6F (111) at 21/25 set to 1              *
* Pixel index of character 0x6F (111) at 21/23 set to 1              *
* Range disabled: 0000 - FFFF                                        *
* Character enabled:   0x6F (111)                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font. A good place would be GUIConf.H
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSpecial32B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSpecial32B_006F[204] = { /* code 006F, LATIN SMALL LETTER O */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,__XXXXXX,XXX_____,________,
  ________,XXXXXXXX,XXXXX___,________,
  ______XX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XXXXXXXX,XXXXXXX_,________,
  ________,XXXXXXXX,XXXXX___,________,
  ________,__XXXXXX,XXX_____,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSpecial32B_CharInfo[1] = {
   {  29,  29,  4, acGUI_FontSpecial32B_006F } /* code 006F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSpecial32B_Prop1 = {
   0x006F /* first character */
  ,0x006F /* last character  */
  ,&GUI_FontSpecial32B_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSpecial32B = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,51 /* height of font  */
  ,51 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSpecial32B_Prop1}
  ,40 /* Baseline */
  ,26 /* Height of lowercase characters */
  ,35 /* Height of capital characters */
};

