/******************************************************************************
*  Generated by PSoC Designer 5.1.1875.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "Counter8_1.h"
#include "Counter8_2.h"
#include "DAC9_1.h"
#include "DUALADC_1.h"
#include "EzI2Cs_1.h"
#include "LED_1.h"
#include "LED_2.h"
#include "PGA_1.h"
#include "PGA_2.h"
#include "PWM8_1.h"
#include "PWM8_2.h"

#endif
