//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_12.h
//   Version: 1.40, Updated on 2011/9/2 at 9:40:1                                          
//  Generated by PSoC Designer 5.1.2309
//
//  DESCRIPTION: LED_12 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_12_INCLUDE
#define LED_12_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_12_Stop
#pragma fastcall16  LED_12_Start
#pragma fastcall16  LED_12_On
#pragma fastcall16  LED_12_Off
#pragma fastcall16  LED_12_Switch
#pragma fastcall16  LED_12_Invert
#pragma fastcall16  LED_12_GetState


//-------------------------------------------------
// Constants for LED_12 API's.
//-------------------------------------------------
//
#define  LED_12_ON   1
#define  LED_12_OFF  0

//-------------------------------------------------
// Prototypes of the LED_12 API.
//-------------------------------------------------
extern void  LED_12_Start(void);                                     
extern void  LED_12_Stop(void);                                      
extern void  LED_12_On(void);                                      
extern void  LED_12_Off(void);                                      
extern void  LED_12_Switch(BYTE bSwitch);
extern void  LED_12_Invert(void);                                         
extern BYTE  LED_12_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
