//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_14.h
//   Version: 1.40, Updated on 2011/9/2 at 9:40:1                                          
//  Generated by PSoC Designer 5.1.2309
//
//  DESCRIPTION: LED_14 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_14_INCLUDE
#define LED_14_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_14_Stop
#pragma fastcall16  LED_14_Start
#pragma fastcall16  LED_14_On
#pragma fastcall16  LED_14_Off
#pragma fastcall16  LED_14_Switch
#pragma fastcall16  LED_14_Invert
#pragma fastcall16  LED_14_GetState


//-------------------------------------------------
// Constants for LED_14 API's.
//-------------------------------------------------
//
#define  LED_14_ON   1
#define  LED_14_OFF  0

//-------------------------------------------------
// Prototypes of the LED_14 API.
//-------------------------------------------------
extern void  LED_14_Start(void);                                     
extern void  LED_14_Stop(void);                                      
extern void  LED_14_On(void);                                      
extern void  LED_14_Off(void);                                      
extern void  LED_14_Switch(BYTE bSwitch);
extern void  LED_14_Invert(void);                                         
extern BYTE  LED_14_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
