//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_11.h
//   Version: 1.40, Updated on 2011/9/2 at 9:40:1                                          
//  Generated by PSoC Designer 5.1.2309
//
//  DESCRIPTION: LED_11 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_11_INCLUDE
#define LED_11_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_11_Stop
#pragma fastcall16  LED_11_Start
#pragma fastcall16  LED_11_On
#pragma fastcall16  LED_11_Off
#pragma fastcall16  LED_11_Switch
#pragma fastcall16  LED_11_Invert
#pragma fastcall16  LED_11_GetState


//-------------------------------------------------
// Constants for LED_11 API's.
//-------------------------------------------------
//
#define  LED_11_ON   1
#define  LED_11_OFF  0

//-------------------------------------------------
// Prototypes of the LED_11 API.
//-------------------------------------------------
extern void  LED_11_Start(void);                                     
extern void  LED_11_Stop(void);                                      
extern void  LED_11_On(void);                                      
extern void  LED_11_Off(void);                                      
extern void  LED_11_Switch(BYTE bSwitch);
extern void  LED_11_Invert(void);                                         
extern BYTE  LED_11_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
