//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_10.h
//   Version: 1.40, Updated on 2011/9/2 at 9:40:1                                          
//  Generated by PSoC Designer 5.1.2309
//
//  DESCRIPTION: LED_10 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_10_INCLUDE
#define LED_10_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_10_Stop
#pragma fastcall16  LED_10_Start
#pragma fastcall16  LED_10_On
#pragma fastcall16  LED_10_Off
#pragma fastcall16  LED_10_Switch
#pragma fastcall16  LED_10_Invert
#pragma fastcall16  LED_10_GetState


//-------------------------------------------------
// Constants for LED_10 API's.
//-------------------------------------------------
//
#define  LED_10_ON   1
#define  LED_10_OFF  0

//-------------------------------------------------
// Prototypes of the LED_10 API.
//-------------------------------------------------
extern void  LED_10_Start(void);                                     
extern void  LED_10_Stop(void);                                      
extern void  LED_10_On(void);                                      
extern void  LED_10_Off(void);                                      
extern void  LED_10_Switch(BYTE bSwitch);
extern void  LED_10_Invert(void);                                         
extern BYTE  LED_10_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
