//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_15.h
//   Version: 1.40, Updated on 2011/9/2 at 9:40:1                                          
//  Generated by PSoC Designer 5.1.2309
//
//  DESCRIPTION: LED_15 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef LED_15_INCLUDE
#define LED_15_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_15_Stop
#pragma fastcall16  LED_15_Start
#pragma fastcall16  LED_15_On
#pragma fastcall16  LED_15_Off
#pragma fastcall16  LED_15_Switch
#pragma fastcall16  LED_15_Invert
#pragma fastcall16  LED_15_GetState


//-------------------------------------------------
// Constants for LED_15 API's.
//-------------------------------------------------
//
#define  LED_15_ON   1
#define  LED_15_OFF  0

//-------------------------------------------------
// Prototypes of the LED_15 API.
//-------------------------------------------------
extern void  LED_15_Start(void);                                     
extern void  LED_15_Stop(void);                                      
extern void  LED_15_On(void);                                      
extern void  LED_15_Off(void);                                      
extern void  LED_15_Switch(BYTE bSwitch);
extern void  LED_15_Invert(void);                                         
extern BYTE  LED_15_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
